package dev.sanskrit.shiksha

enum class Samjna {
    VRDDHI, GUNA, IK, AC, HAL, SAMYOGA, ANUNASIKA, SAVARNA,
    DHATU, PRATYAYA, ANGA, PADA, PRAGRHYA, SARVANAMA, BHA, GHI,
    NADI, APRUKTA, SAMBUDDHI, SARVANAMASTHANA, GHU, PRATIPADIKA,
    AVYAYA, NIPATA, GATI, UPASARGA, ABHYASA
}

enum class Accent {
    UDATTA, ANUDATTA, SVARITA,
    ADYUDATTA, ANTODATTA, MADHYODATTA
}

enum class Recension {
    KASHIKA, SIDDHANTA_KAUMUDI, MAHABHASHYA, SHAKATAYANA
}

enum class ItStatus {
    SET, ANIT, VET
}

enum class Karmatva {
    SAKARMAKA, AKARMAKA, DVIKARMAKA
}

/** The lexical sense in which a particular term is being derived. */
enum class LexicalUse {
    RELATIVE_POSITION,
    PROPER_NAME,
    KINSHIP,
    WEALTH,
    EXTERIOR_ASSOCIATION,
    GARMENT,
}

enum class SemanticFeature {
    KARTARI, STRI, PRATHAMA, EKAVACANA, BHAVISYAT, APADANA, UNADI_LICENSED,
    SAMUHA, VISHAYA_DESE, ADHYAYANA_VEDANA, NIVASA, CHATURARTHIKA, JATA,
    KALAVRTTI, TATRA_BHAVA, VYAKHYANA, TATAH_AGATA, ABHIJANA, GOTRA,
    PRAGDIVYATIYA, SVANGA, APATYA, UDICYA, GUNA_REQUEST, VRDDHI_REQUEST,
    ARDHADHATUKA, ASATTVA, KRIYAYOGA, TADRAJA, BHAVE, KARTR_VEDANA,
    SAPTAMI, BAHUVACANA, VARTAMANA,
    DVITIYA, TRTIYA, CHATURTHI, PANCHAMI, SASTHI, DVIVACANA
}
