package dev.panini.ganapatha

object MayuravyamsakadiGana : Gana(
    name = "मयूरव्यंसकादिः",
    sourceIndex = 15,
    sutra = "2.1.72",
    sutraId = "21072",
    sutraText = "मयूरव्यंसकादयश्च",
    sutraTransliteration = "mayooravyamsakaadayashcha",
    kind = GanaKind.AKRTI,
    notes = "Source row contains several contextual annotations; only member entries are modeled here.",
    members = ganaMembers {
        member("मयूरव्यंसक")
        member("छात्रव्यंसक")
        member("कम्बोजमुण्ड")
        member("यवनमुण्ड")
        member("हस्तगृह्य")
        member("पादेगृह्य")
        member("पादगृह्य")
        member("लाङ्गूलेगृह्य")
        member("लाङ्गूलगृह्य")
        member("पुनर्दाय")
        member("एहीडम्")
        member("एहियवम्")
        member("अपेहिवाणिजा")
        member("प्रेहिवाणिजा")
        member("एहिस्वागता")
        member("अपोहिस्वागता")
        member("प्रेहिस्वागता")
        member("एहिद्वितीया")
        member("अपेहिद्वितीया")
        member("प्रेहिद्वितीया")
        member("एहिकटा")
        member("अपोहकटा")
        member("प्रोहकटा")
        member("आहरकटा")
        member("प्रोहिकर्दमा")
        member("प्रोहकर्दमा")
        member("विधमचूडा")
        member("उद्धमचूडा")
        member("उद्धरचूडा")
        member("आहरचेला")
        member("हरवसन")
        member("आहरवनिता")
        member("हतविनत")
        member("कृन्तविचक्षणा")
        member("उद्धरोत्सृजा")
        member("उद्धरावसृजा")
        member("उद्धमविधमा")
        member("उत्पचनिपचा")
        member("उत्पतनिपता")
        member("उच्चावचम्")
        member("उच्चनीचम्")
        member("अचोपचम्")
        member("आपराचम्")
        member("खप्रचम")
        member("निश्चप्रचम्")
        member("अकिंचन")
        member("स्नात्वाकालक")
        member("पीत्वास्थिरक")
        member("भुक्त्वासुहित")
        member("प्रोष्यपापीयान्")
        member("उत्पत्यपाकला")
        member("निपत्यरोहिणी")
        member("निषण्णाश्यामा")
        member("अप्रेहिप्रघसा")
        member("प्रेहिप्रघसा")
        member("इहपञ्चमी")
        member("इहद्वितीया")
        member("जहिजोड")
        member("जहिजोडम्")
        member("जहिस्तम्बः")
        member("ज्जहिस्तम्बम")
        member("अश्नीतपिबता")
        member("पचतभृज्जता")
        member("खादतमोदता")
        member("खादतवमता")
        member("खादताचमता")
        member("आहरनिवपा")
        member("आवपनिष्किरा")
        member("उत्पचच्विपचा")
        member("भिन्धिलवणा")
        member("कृन्धिविचक्षना")
        member("पचलवणा")
        member("पचप्रकूटा")
        member("अकुतोभयः")
        member("कान्दिशीकः")
        member("कान्दोशीकः")
        member("स्त्राहोपुरुषिका")
        member("अहमहमिका")
        member("यदृच्छा")
        member("एहिरेयाहिरा")
        member("उन्मृजावमृजा")
        member("द्रव्यान्तरम्")
        member("अवश्यकार्यम्")
    },
)
