package dev.panini.ganapatha

import dev.panini.shiksha.Accent
import dev.panini.shiksha.Samjna

object SvaradiGana : Gana(
    name = "स्वरादिः",
    sourceIndex = 2,
    sutra = "1.1.37",
    sutraId = "11037",
    sutraText = "स्वरादिनिपातमव्ययम्",
    sutraTransliteration = "svaraadinipaatamavyayam",
    kind = GanaKind.AKRTI,
    resultSamjnas = setOf(Samjna.AVYAYA),
    sanskritMeaning = "स्वरादिगणस्य शब्दाः, निपातसंज्ञकाः शब्दाः च अव्ययसंज्ञकाः भवन्ति ।",
    englishMeaning = "The words of the स्वरादिगण and the words which are called 'निपात' are all also known as 'अव्यय'.",
    members = ganaMembers {
        member("स्वर्", accent = Accent.ANTODATTA)
        member("अन्तर्", accent = Accent.ANTODATTA)
        member("प्रातर्", accent = Accent.ANTODATTA)

        member("पुनर्", accent = Accent.ADYUDATTA)
        member("सनुतर्", accent = Accent.ADYUDATTA)
        member("उच्चैस्", accent = Accent.ADYUDATTA)
        member("नीचैस्", accent = Accent.ADYUDATTA)
        member("शनैस्", accent = Accent.ADYUDATTA)
        member("ऋधक्", accent = Accent.ADYUDATTA)
        member("ऋते", accent = Accent.ADYUDATTA)
        member("युगपत्", accent = Accent.ADYUDATTA)
        member("आरात्", accent = Accent.ADYUDATTA)
        member("अन्तिकात्", accent = Accent.ADYUDATTA)
        member("पृथक्", accent = Accent.ADYUDATTA)

        member("ह्यस्")
        member("श्वस्")
        member("दिवा")
        member("रात्रौ")
        member("सायम्")
        member("चिरम्")
        member("मनाक्")
        member("ईषत्")
        member("शश्वत्")
        member("जोषम्")
        member("तूष्णीम्")
        member("बहिस्")
        member("अधस्")
        member("अवस्")
        member("समया")
        member("निकषा")
        member("स्वयम्")
        member("मृषा")
        member("नक्तम्")
        member("नञ्")
        member("हेतौ")
        member("हे")
        member("है")
        member("इद्धा")
        member("अद्धा")
        member("सामि")

        member("वत्", isInstruction = true, condition = "यथा ब्राह्मणवत्, क्षत्रियवत्")

        member("सना")
        member("सनत्")
        member("सनात्")
        member("उपधा")
        member("तिरस्")
        member("अन्तरा", accent = Accent.ANTODATTA)
        member("अन्तरेण")
        member("मक्")
        member("ज्योक्")
        member("योक्")
        member("नक्")
        member("कम्")
        member("शम्")
        member("सहसा")
        member("श्रद्धा")
        member("अलम्")
        member("स्वधा")
        member("वषट्")
        member("विना")
        member("नाना")
        member("स्वस्ति")
        member("अन्यत्")
        member("अस्ति")
        member("उपांशु")
        member("क्षमा")
        member("विहायसा")
        member("दोषा")
        member("मुधा")
        member("दिष्ट्या")
        member("वृथा")
        member("मिथ्या")

        member("क्तवातोसुन्कसुनः", isInstruction = true)
        member("कृन्मकारसन्ध्यक्षरान्तोऽव्ययीभावश्च", isInstruction = true)

        member("पुरा")
        member("मिथो")
        member("मिथस्")
        member("प्रायस्")
        member("मुहुस्")
        member("प्रवाहुकम्")
        member("प्रवाहिका")
        member("आर्यहलम्")
        member("अभीक्ष्णम्")
        member("साकम्")
        member("सार्धम्")
        member("सार्थम्")
        member("सत्रम्")
        member("समम्")
        member("नमस्")
        member("हिरुक्")

        member("तसिलादयस्तद्धित एधाच्चपर्यन्ताः", isInstruction = true)
        member("शस्तसी", isInstruction = true)
        member("कृत्वसुच्", isInstruction = true)
        member("सुच्", isInstruction = true)
        member("आस्थालौ", isInstruction = true)
        member("च्व्यर्थाश्च", isInstruction = true)

        member("अथ")
        member("अम्")
        member("आम्")
        member("प्रताम्")
        member("प्रतान्")
        member("प्रशान्")
        member("तथाहि")
        member("मा")
        member("माङ्")
        member("श्रम्")
        member("कामम्")
        member("प्रकामम्")
        member("भूयस्")
        member("परम्")
        member("साक्षात्")
        member("साचि")
        member("सावि")
        member("सत्यम्")
        member("मंक्षु")
        member("संवत्")
        member("अवश्यम्")
        member("सपदि")
        member("प्रादुस्")
        member("आविस्")
        member("अनिशम्")
        member("नित्यम्")
        member("नित्यदा")
        member("सदा")
        member("अजस्रम्")
        member("सन्ततम्")
        member("उषा")
        member("ओम्")
        member("भूर्")
        member("भुवर्")
        member("झटिति")
        member("तरसा")
        member("सुष्ठु")
        member("कु")
        member("अञ्जसा")
        member("अ")
        member("मिथु")
        member("अमिथु")
        member("विथक्")
        member("भाजक्")
        member("अन्वक्")
        member("चिराय")
        member("चिररात्राय")
        member("चिरस्य")
        member("चिरेण")
        member("चिरात्")
        member("अस्तम्")
        member("आनुषक्")
        member("अनुषक्")
        member("अनुषट्")
        member("अम्नस्")
        member("अम्भस्")
        member("अम्नर्")
        member("अम्भर्")
        member("स्थाने")
        member("वरम्")
        member("दुष्ठु")
        member("बलात्")
        member("शु")
        member("अर्वाक्")
        member("शुदि")
        member("वदि")

        member("तसिलादयः प्राक्पाशपाः", isInstruction = true)
        member("शस्प्रभृतयः प्राक्समासान्तेभ्यः", isInstruction = true)
        member("मान्तः कृत्वोर्थः", isInstruction = true)
        member("नानाञौ", isInstruction = true)
    },
)
