package dev.panini.ashtadhyayi.adhyaya3.pada1

import dev.panini.sutra.Sutra

object Adhyaya3Pada1 {
    val sutras: List<Sutra<*, *>> = listOf(
        PratyayahSutra,
        DhatohSutra,
        GupTijKitsadbhyahSanSutra,
        DhatohKarmanahSamanakartrkadIcchayamSanSutra,
        BhrshadibhyoBhuvyacverLopashCaHalahSutra,
        LohitadidajbhyahKyashSutra,
        SukhadibhyoKartrvedanayamSutra,
        KandvadibhyoYakSutra,
        DhatorEkayacoHaladerKriyasamabhihareYangSutra,
        HetumatiCaSutra,
        GupDhoopVichchhiPaniPanibhyOyaSutra,
        RtIyIyAnehKyanSutra,
        KamerNingSutra,
        SanaadyantaDhatavahSutra,
        KasPratyayadAmAmantreLitSutra,
        IjashChaSutra,
        UshavidajabhyashChaSutra,
        KrnChanuprayujyateLitSutra,
        NandigrahipacadibhyoLyuninyacahSutra,
        CuradibhyoNicSutra,
        CliLungiSutra,
        ClehSicSutra,
        ShalIgupadhadAnitahKsahSutra,
        NishriDruSruBhyahKarthariChaSutra,
        PusAdiDyutAdyLdtahParasmaipadesuSutra,
        ChinKarmaniChaSutra,
        SarvadhatukeYakSutra,
        SibbahulamLetiSutra,
        KartariShapSutra,
        DivadibhyahShyanSutra,
        SvadibhyahShnuhSutra,
        TudadibhyahShahSutra,
        RudhadibhyahShnamSutra,
        TanadiKrnjbhyahUhSutra,
        KryadibhyahShnaSutra,
        KrdAtinSutra,
        TavyattavyaaniyarahSutra,
        AcoYatSutra,
        EtiStuShaasVriDrJuShyahKyapSutra,
        RhalorNyatSutra,
        NvultrcauSutra,
        GeheKahSutra,
        SilpiniShvunSutra,
        VyatyayoBahulamSutra,
        SyatasiLrlrtohSutra,
    )
}
