package dev.sanskrit.pratyahara

import dev.sanskrit.shiksha.Vyanjana
import dev.sanskrit.shiksha.Svara

object MaheshvaraSutras {
    val all: List<MaheshvaraSutra> = listOf(
        MaheshvaraSutra()
            .add(Svara.A)
            .add(Svara.I)
            .add(Svara.U)
            .marker(ItMarker.N),
        MaheshvaraSutra()
            .add(Svara.R)
            .add(Svara.L)
            .marker(ItMarker.K),
        MaheshvaraSutra()
            .add(Svara.E)
            .add(Svara.O)
            .marker(ItMarker.NG),
        MaheshvaraSutra()
            .add(Svara.AI)
            .add(Svara.AU)
            .marker(ItMarker.C),
        MaheshvaraSutra()
            .add(Vyanjana.HA)
            .add(Vyanjana.YA)
            .add(Vyanjana.VA)
            .add(Vyanjana.RA)
            .marker(ItMarker.TT),
        MaheshvaraSutra()
            .add(Vyanjana.LA)
            .marker(ItMarker.NN),
        MaheshvaraSutra()
            .add(Vyanjana.NYA)
            .add(Vyanjana.MA)
            .add(Vyanjana.NGA)
            .add(Vyanjana.NNA)
            .add(Vyanjana.NA)
            .marker(ItMarker.M),
        MaheshvaraSutra()
            .add(Vyanjana.JHA)
            .add(Vyanjana.BHA)
            .marker(ItMarker.NY),
        MaheshvaraSutra()
            .add(Vyanjana.GHA)
            .add(Vyanjana.DDHA)
            .add(Vyanjana.DHA)
            .marker(ItMarker.SH),
        MaheshvaraSutra()
            .add(Vyanjana.JA)
            .add(Vyanjana.BA)
            .add(Vyanjana.GA)
            .add(Vyanjana.DDA)
            .add(Vyanjana.DA)
            .marker(ItMarker.SHA),
        MaheshvaraSutra()
            .add(Vyanjana.KHA)
            .add(Vyanjana.PHA)
            .add(Vyanjana.CHA)
            .add(Vyanjana.TTHA)
            .add(Vyanjana.THA)
            .add(Vyanjana.CA)
            .add(Vyanjana.TTA)
            .add(Vyanjana.TA)
            .marker(ItMarker.V),
        MaheshvaraSutra()
            .add(Vyanjana.KA)
            .add(Vyanjana.PA)
            .marker(ItMarker.Y),
        MaheshvaraSutra()
            .add(Vyanjana.SHA)
            .add(Vyanjana.SSA)
            .add(Vyanjana.SA)
            .marker(ItMarker.R),
        MaheshvaraSutra()
            .add(Vyanjana.HA)
            .add(Vyanjana.LA)
            .marker(ItMarker.L),
    )
}
