package dev.panini.ganapatha

object AshvadiGana : Gana(
    name = "अश्वादिः",
    sourceIndex = 60,
    sutra = "4.1.110",
    sutraId = "41110",
    sutraText = "अश्वादिभ्यः फञ्",
    sutraTransliteration = "ashvaadibhyahaphany",
    kind = GanaKind.PATHA,
    notes = "Source row contains contextual annotations; only member entries are modeled here.",
    members = ganaMembers {
        member("अश्व")
        member("अश्मन्")
        member("शङ्ख")
        member("शूदक")
        member("विद")
        member("पुट")
        member("रोहिण")
        member("खर्जूर")
        member("खजूर")
        member("ञ्जार")
        member("वस्")
        member("पिजूर")
        member("भडिल")
        member("भण्डिल")
        member("भडित")
        member("भण्डित")
        member("प्रकृत")
        member("रामोद")
        member("क्षान्त")
        member("काश")
        member("तीक्ष्ण")
        member("गोलाङ्क")
        member("अर्क")
        member("स्वर")
        member("स्फुट")
        member("चक्र")
        member("श्रविष्")
        member("पविन्द")
        member("पवित्र")
        member("गोमिन्")
        member("श्याम")
        member("धूम")
        member("धूम्र")
        member("वाग्मिन्")
        member("विश्वानर")
        member("कुट")
        member("शप")
        member("अत्रेये")
        member("जन")
        member("जड")
        member("खड")
        member("ग्रीष्म")
        member("अर्ह")
        member("कित")
        member("विंशप")
        member("विशाल")
        member("गिरि")
        member("चपल")
        member("चुप")
        member("दासक")
        member("वैल्य")
        member("बैल्व")
        member("प्राच्य")
        member("धर्म्य")
        member("आनडुह्य")
        member("अर्जुन")
        member("प्रहृत")
        member("सुमनस्")
        member("दुर्मनस्")
        member("मन")
        member("मनन")
        member("प्रान्त")
        member("ध्वन")
        member("आत्रेय")
        member("भरद्वाजे")
        member("भरद्वाज")
        member("आत्रेये")
        member("इत्स")
        member("आतव")
        member("कितव")
        member("वद")
        member("धन्य")
        member("पाद")
        member("शिव")
        member("खदिर")
    },
)
