package dev.panini.ganapatha

object ShivadiGana : Gana(
    name = "शिवादिः",
    sourceIndex = 61,
    sutra = "4.1.112",
    sutraId = "41112",
    sutraText = "शिवादिभ्योऽण्",
    sutraTransliteration = "shivaadibhyon",
    kind = GanaKind.AKRTI,
    notes = "Source row contains contextual annotations; only member entries are modeled here.",
    members = ganaMembers {
        member("शिव")
        member("प्रोष्ठ")
        member("प्रोष्ठिक")
        member("चण्ड")
        member("जम्भ")
        member("भूरि")
        member("दण्ड")
        member("कुठार")
        member("ककुभ्")
        member("ककुभा")
        member("अनभिम्लान")
        member("कोहित")
        member("सुख")
        member("संधि")
        member("मुनि")
        member("ककुत्स्थ")
        member("कहोड")
        member("कोहड")
        member("कहूय")
        member("कहय")
        member("रोद")
        member("कपिञ्जल")
        member("कुपिञ्जल")
        member("खञ्जन")
        member("वतण्ड")
        member("तृणकर्ण")
        member("क्षीरह्रद")
        member("जलह्रद")
        member("परिल")
        member("पथिक")
        member("पिष्ट")
        member("हैहय")
        member("ार्षिक")
        member("गोपिका")
        member("कपिलिका")
        member("जटिलिका")
        member("अलेखन")
        member("विश्रवण")
        member("रवण")
        member("वर्तनाक्ष")
        member("ग्रीवाक्ष")
        member("पिटक")
        member("विटप")
        member("पिटाक")
        member("तृक्षाक")
        member("नभक")
        member("ऊर्णनाभ")
        member("चरत्कारु")
        member("पृथा")
        member("उत्क्षेप")
        member("पुरोहितिका")
        member("सुरोहितिका")
        member("सुरोहिका")
        member("आर्यश्वेत")
        member("अर्यश्वेत")
        member("सुपिष्ट")
        member("मसुरकर्ण")
        member("मयूरकर्ण")
        member("र्जूरकर्")
        member("कदूरक")
        member("तक्षन्")
        member("ऋष्टिषेण")
        member("गङ्गा")
        member("विपाश")
        member("मस्क")
        member("लह्य")
        member("द्रुह्य")
        member("अयस्थूण")
        member("तृणकर्ण")
        member("तृण")
        member("कर्ण")
        member("पर्ण")
        member("भलन्दन")
        member("विरूपाक्ष")
        member("भूमि")
        member("इला")
        member("सपत्नी")
    },
)
