package dev.panini.compiler

import dev.panini.core.Karaka
import dev.panini.execution.ExecutionBindingResult
import dev.panini.execution.ExecutionExpression
import dev.panini.execution.ExecutionPlan
import dev.panini.execution.ExecutionPlanner
import dev.panini.execution.PlanningResult
import dev.panini.execution.SambhashanaContext
import dev.panini.execution.SanskritUktiInput
import dev.panini.execution.SanskritValue
import dev.panini.execution.ValueEnvironment
import dev.panini.execution.bindingName
import dev.panini.execution.binding.VyakaranamExecutionAdapter
import dev.panini.execution.sutra.ExecutableUktiSutraCompiler
import dev.panini.execution.sutra.ProgramBlueprintContext
import dev.panini.execution.sutra.ProgramBlueprintGranthaPlanner
import dev.panini.execution.sutra.ProgramGranthaPlanning

/** Plans only self-contained leaves whose operands can be embedded in generated bytecode. */
internal object DirectLeafPlanner {
    private val supportedOperations = setOf(
        "सङ्ख्यायोजनम्",
        "सङ्ख्यावियोगः",
        "सङ्ख्यागुणनम्",
        "सङ्ख्याहरणम्",
        "सङ्ख्याशेषः",
        "सङ्ख्यातुलना",
        "सूच्याकारः",
        "सूचीसंयोगः",
        "सूचीसंयोजनम्",
        "सूचीसङ्क्षेपः",
        "सूचीनिक्षेपणम्",
        "सूचीस्थानम्",
        "सूचीविभागः",
        "सूचीविलोमः",
        "सूचीप्रसारणम्",
        "सूचीशोधनम्",
        "सूच्युद्धरणम्",
        "सूच्यस्तित्वम्",
        "प्रत्येकवृत्तिः",
        "विजयः",
        "प्रदर्शनम्",
    )

    fun plan(
        source: String,
        environment: ValueEnvironment = ValueEnvironment(),
        allowStore: Boolean = false,
    ): ExecutionPlan? = plans(source, environment, allowStore)?.singleOrNull()

    fun resultBindingName(source: String): String? {
        val segmentedSource = source.replace("+", " + ").replace(Regex("\\s+"), " ").trim()
        val conversation = SambhashanaContext("प्रयोक्ता", "यन्त्रम्")
        val input = SanskritUktiInput(
            speaker = conversation.speaker,
            listener = conversation.listener,
            text = segmentedSource,
        )
        val invocation = ((runCatching {
            VyakaranamExecutionAdapter.bind(input, conversation)
        }.getOrNull() as? ExecutionBindingResult.Bound)?.ukti?.invocations)?.singleOrNull() ?: return null
        val operation = invocation.selectedOperation?.let { selected ->
            invocation.dhatu.operations.singleOrNull { it.name == selected }
        } ?: invocation.dhatu.operations.singleOrNull { it.resultBindingKaraka != null }
        val karaka = operation?.resultBindingKaraka ?: return null
        return invocation.bindings[karaka]?.bindingName()
    }

    fun plans(
        source: String,
        environment: ValueEnvironment = ValueEnvironment(),
        allowStore: Boolean = false,
    ): List<ExecutionPlan>? {
        val segmentedSource = source.replace("+", " + ").replace(Regex("\\s+"), " ").trim()
        val conversation = SambhashanaContext(
            "प्रयोक्ता",
            "यन्त्रम्",
            previousResults = environment.values["LastResult"]?.let {
                mapOf("LastResult" to it.toDisplayText())
            }.orEmpty(),
            previousTypedResults = environment.values,
        )
        val input = SanskritUktiInput(
            speaker = conversation.speaker,
            listener = conversation.listener,
            text = segmentedSource,
        )
        val ukti = (runCatching { VyakaranamExecutionAdapter.bind(input, conversation) }.getOrNull()
            as? ExecutionBindingResult.Bound)?.ukti ?: return null
        val program = when (val planned = ProgramBlueprintGranthaPlanner.plan(
            ExecutableUktiSutraCompiler.compileBlueprintGrantha(ukti),
            ProgramBlueprintContext(
                speaker = ukti.speaker,
                listener = ukti.listener,
                text = ukti.text,
                prayojana = ukti.prayojana,
                polarity = ukti.polarity,
                lakara = ukti.lakara,
            ),
        )) {
            is ProgramGranthaPlanning.Success -> planned.program
            is ProgramGranthaPlanning.Invalid -> return null
        }
        val plans = (ExecutionPlanner.plan(program, environment) as? PlanningResult.Planned)
            ?.plans ?: return null
        return plans.takeIf { candidates -> candidates.isNotEmpty() && candidates.all { plan ->
            (plan.resolved.operation.name in supportedOperations ||
                (allowStore && plan.resolved.operation.name == "मूल्यदानम्")) &&
                (plan.resolved.operation.name != "सङ्ख्यातुलना" ||
                    (plan.resolved.operation.trigger.requiredUpasargas.isEmpty() &&
                        plan.resolved.operation.trigger.requiredAvyayas.isEmpty())) &&
                (plan.resolved.operation.name != "विजयः" ||
                    plan.resolved.operation.trigger.requiredUpasargas == setOf("वि")) &&
                (plan.resolved.operation.name != "प्रदर्शनम्" ||
                    plan.resolved.context.bindings
                        .filterKeys { it in setOf(Karaka.KARMAN, Karaka.APADANA, Karaka.ADHIKARANA) }
                        .values.all { isConcrete(it, environment) }) &&
                plan.resolved.context.bindings.values.all { isEmbeddable(it, environment) }
        } }
    }

    private fun isConcrete(
        expression: ExecutionExpression,
        environment: ValueEnvironment,
    ): Boolean = when (expression) {
        is ExecutionExpression.Pada -> expression.value is SanskritValue.Sankhya
        is ExecutionExpression.TypedOperand -> isSupportedConstant(expression.value)
        is ExecutionExpression.Coordination -> expression.members.all { isConcrete(it, environment) }
        is ExecutionExpression.Reference -> expression.name in environment.values
    }

    private fun isEmbeddable(
        expression: ExecutionExpression,
        environment: ValueEnvironment,
    ): Boolean = when (expression) {
        is ExecutionExpression.Pada -> expression.value?.let(::isSupportedConstant) ?: true
        is ExecutionExpression.TypedOperand -> isSupportedConstant(expression.value)
        is ExecutionExpression.Coordination -> expression.members.all { isEmbeddable(it, environment) }
        is ExecutionExpression.Reference -> expression.name in environment.values
    }

    private fun isSupportedConstant(value: SanskritValue): Boolean = when (value) {
        is SanskritValue.Sankhya,
        is SanskritValue.Range,
        is SanskritValue.Rational,
        is SanskritValue.Shabda,
        is SanskritValue.Gana,
        is SanskritValue.Suchi,
        is SanskritValue.Rupa,
        is SanskritValue.Satya,
        SanskritValue.Lopa,
        -> true
    }
}
