package dev.panini.compiler

import dev.panini.execution.SanskritValue
import dev.panini.shiksha.Samjna
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes.AASTORE
import org.objectweb.asm.Opcodes.ACONST_NULL
import org.objectweb.asm.Opcodes.ANEWARRAY
import org.objectweb.asm.Opcodes.DUP
import org.objectweb.asm.Opcodes.INVOKESTATIC

/** Materializes the complete recursive [SanskritValue] hierarchy in generated bytecode. */
internal object StructuredValueBytecodeEmitter {
    fun emit(mv: MethodVisitor, value: SanskritValue) {
        when (value) {
            is SanskritValue.Sankhya -> {
                mv.visitLdcInsn(value.value)
                mv.visitLdcInsn(value.word)
                call(mv, "sankhya", "(JLjava/lang/String;)Ldev/panini/execution/SanskritValue;")
            }
            is SanskritValue.Range -> {
                emit(mv, value.minimum)
                mv.visitTypeInsn(org.objectweb.asm.Opcodes.CHECKCAST, "dev/panini/execution/SanskritValue\$Sankhya")
                emit(mv, value.maximum)
                mv.visitTypeInsn(org.objectweb.asm.Opcodes.CHECKCAST, "dev/panini/execution/SanskritValue\$Sankhya")
                call(mv, "range", "(Ldev/panini/execution/SanskritValue\$Sankhya;Ldev/panini/execution/SanskritValue\$Sankhya;)Ldev/panini/execution/SanskritValue;")
            }
            is SanskritValue.Rational -> {
                mv.visitLdcInsn(value.numerator)
                mv.visitLdcInsn(value.denominator)
                mv.visitLdcInsn(value.word)
                call(mv, "rational", "(JJLjava/lang/String;)Ldev/panini/execution/SanskritValue;")
            }
            is SanskritValue.Shabda -> {
                mv.visitLdcInsn(value.text)
                emitStringArray(mv, value.samjnas.map(::encodeSamjna))
                call(mv, "shabdaWithEncodedSamjnas", "(Ljava/lang/String;[Ljava/lang/String;)Ldev/panini/execution/SanskritValue;")
            }
            is SanskritValue.Gana -> {
                emitValueArray(mv, value.elements)
                call(mv, "gana", "([Ldev/panini/execution/SanskritValue;)Ldev/panini/execution/SanskritValue;")
            }
            is SanskritValue.Suchi -> {
                emitValueArray(mv, value.items)
                call(mv, "suchi", "([Ldev/panini/execution/SanskritValue;)Ldev/panini/execution/SanskritValue;")
            }
            is SanskritValue.Rupa -> {
                mv.visitLdcInsn(value.schema)
                emitStringArray(mv, value.fields.keys.toList())
                emitValueArray(mv, value.fields.values.toList())
                call(mv, "rupa", "(Ljava/lang/String;[Ljava/lang/String;[Ldev/panini/execution/SanskritValue;)Ldev/panini/execution/SanskritValue;")
            }
            is SanskritValue.Satya -> {
                mv.visitInsn(if (value.boolean) org.objectweb.asm.Opcodes.ICONST_1 else org.objectweb.asm.Opcodes.ICONST_0)
                value.surface?.let(mv::visitLdcInsn) ?: mv.visitInsn(ACONST_NULL)
                call(mv, "satya", "(ZLjava/lang/String;)Ldev/panini/execution/SanskritValue;")
            }
            SanskritValue.Lopa -> call(mv, "lopa", "()Ldev/panini/execution/SanskritValue;")
        }
    }

    private fun emitValueArray(mv: MethodVisitor, values: List<SanskritValue>) {
        mv.visitLdcInsn(values.size)
        mv.visitTypeInsn(ANEWARRAY, "dev/panini/execution/SanskritValue")
        values.forEachIndexed { index, value ->
            mv.visitInsn(DUP)
            mv.visitLdcInsn(index)
            emit(mv, value)
            mv.visitInsn(AASTORE)
        }
    }

    private fun emitStringArray(mv: MethodVisitor, values: List<String>) {
        mv.visitLdcInsn(values.size)
        mv.visitTypeInsn(ANEWARRAY, "java/lang/String")
        values.forEachIndexed { index, value ->
            mv.visitInsn(DUP)
            mv.visitLdcInsn(index)
            mv.visitLdcInsn(value)
            mv.visitInsn(AASTORE)
        }
    }

    private fun encodeSamjna(samjna: Samjna): String = when (samjna) {
        is Samjna.Rudhi -> "RUDHI:${samjna.word}"
        is Enum<*> -> samjna.name
    }

    private fun call(mv: MethodVisitor, name: String, descriptor: String) {
        mv.visitMethodInsn(INVOKESTATIC, "dev/panini/compiler/PaniniRuntime", name, descriptor, false)
    }
}
