package dev.panini.ashtadhyayi.adhyaya2.pada2

import dev.panini.sutra.Sutra

object Adhyaya2Pada2 {
    val sutras: List<Sutra<*, *>> = listOf(
        PurvaparakadharottaramEkadesinaSutra,
        ArdhamNapunsakamSutra,
        TrtiyaprabhrtinyAnyatarasyamSutra,
        AntaramBahiryogeUpasamvyanayoscaSutra,
        NanjSutra,
        UpapadamAtingSutra,
        ShashthiSutra,
        YajakadibhishchaSutra,
        AnekamAnyapadartheSutra,
        TenaSahetiTulyayogesutra,
        TatraTenedamitiSarupeSutra,
        CartheDvandvahSutra,
        NityamKridajivikayohSutra,
        KuGatiPradayahSutra,
        AbhyarhitamChaSutra,
        AjadyadantamSutra,
        AlpactaramSutra,
        NaNirdhareSutra,
        UpasarjanamPurvamSutra,
        KarmaniChaSutra,
        AmaivavyayenaSutra,
        KtenaChAPujayamSutra,
        AdhikaranavacinasChaSutra,
        TrjjakabhyamKartariSutra,
        KartariChaSutra,
        EsadAkaPratyayaYukteSutra,
        PuranaGunasuhitaSutra,
        PraptapanneChADvitiyayaSutra,
        TrtiyaprabhrtinyAnyatarasyamExtSutra,
        RajadantadisuSutra,
        SaptamiVisesaneBahuvrihauSutra,
        NisthaBahuvrihauSutra,
        UpapadamAtingExtSutra,
        AnekamAnyapadartheExtSutra,
        SahaSupaSutra,
        CartheDvandvaExtSutra,
        VahitagnyadisuSutra,
        ShashthiExtSutra,
        SesoBahuvrihiSutra,
        AnekamAnyapadartheHeaderSutra,
        AlpactaramExtSutra,
        KadaradahKarmadharayeSutra,
        NityamKridajivikayohExtSutra,
        KuGatiPradayahExtSutra,
        TenaSahetiTulyayogeExtSutra,
        TatraTenedamitiSarupeExtSutra,
        AjadyadantamExtSutra,
        KarmaniChaExtSutra,
        AmaivavyayenaExt2Sutra,
        TenaSahetiHeaderSutra,
        AbhyarhitamChaExtSutra,
        CaturthiTadarthartheExtSutra,
    )
}
