package dev.sanskrit.ganapatha

object ChadiGana : Gana(
    name = "चादिः",
    sourceIndex = 3,
    sutra = "1.4.57",
    sutraId = "14057",
    sutraText = "चादयोऽसत्त्वे",
    sutraTransliteration = "chaadayosattve",
    kind = GanaKind.AKRTI,
    resultSamjnas = setOf(dev.sanskrit.shiksha.Samjna.NIPATA),
    sanskritMeaning = "चादिगणे निर्दिष्टाः शब्दाः अद्रव्यवाचिनि अर्थे निपातसंज्ञकाः भवन्ति ।",
    hindiMeaning = "चादिगण में निर्दिष्ट शब्द द्रव्यवाचक अर्थ न होने पर निपात कहलाते हैं।",
    englishMeaning = "The words included in the चादिगण are called निपात when used in a sense that does not denote an object.",
    members = ganaMembers {
        member("च", "और, भी", "and, also")
        member("वा", "या, अथवा", "or, alternatively")
        member("ह", "ही, निश्चय ही", "indeed, surely")
        member("अह", "एक अव्यय निपात", "an indeclinable particle")
        member("एव", "ही, केवल", "only, just, indeed")
        member("एवम्", "इस प्रकार, ऐसा", "thus, in this way")
        member("नूनम्", "निश्चय ही, अवश्य", "certainly, surely")
        member("शश्वत्", "सदा, निरन्तर", "always, continually")
        member("युगपत्", "एक साथ", "simultaneously")
        member("भूयस्", "अधिक, फिर", "more, again")
        member("सूपत्", "एक अव्यय निपात", "an indeclinable particle")
        member("कूपत्", "एक अव्यय निपात", "an indeclinable particle")
        member("कुवित्", "क्या कभी, शायद", "whether, perhaps")
        member("नेत्", "कहीं नहीं, ऐसा न हो कि", "lest, not so")
        member("चेत्", "यदि", "if")
        member("चण्", "एक अव्यय निपात", "an indeclinable particle")
        member("कच्चित्", "क्या, कहीं", "whether, perhaps")
        member("यत्र", "जहाँ", "where")
        member("तत्र", "वहाँ", "there")
        member("नह", "नहीं", "not")
        member("हन्त", "अच्छा, अहो", "well, alas, come now")
        member("माकिम्", "कदापि नहीं", "by no means")
        member("माकीम्", "कदापि नहीं", "by no means")
        member("माकिर्", "कदापि नहीं", "by no means")
        member("नकिम्", "कुछ नहीं", "nothing, not at all")
        member("नकीम्", "कुछ नहीं", "nothing, not at all")
        member("नकिर्", "कुछ नहीं", "nothing, not at all")
        member("आकीम्", "एक अव्यय निपात", "an indeclinable particle")
        member("माङ", "मत, नहीं", "do not, not")
        member("नञ्", "नहीं, अ-", "not, un-")
        member("तावत्", "इतना, तब तक", "so much, until then")
        member("यावत्", "जितना, जब तक", "as much as, as long as")
        member("त्वा", "एक अव्यय निपात", "an indeclinable particle")
        member("त्वै", "एक अव्यय निपात", "an indeclinable particle")
        member("द्वै", "एक अव्यय निपात", "an indeclinable particle")
        member("न्वै", "निश्चय ही", "indeed, surely")
        member("रै", "अरे, हे", "hey, O")
        member("रे", "अरे, हे", "hey, O")
        member("श्रौषट्", "यज्ञ में प्रयुक्त उद्गार", "a sacrificial exclamation")
        member("वौषट्", "यज्ञ में प्रयुक्त उद्गार", "a sacrificial exclamation")
        member("स्वाहा", "हवन में आहुति का शब्द", "svaha, an oblation cry")
        member("वषट्", "यज्ञ में प्रयुक्त उद्गार", "vashat, a sacrificial cry")
        member("स्वधा", "पितरों के लिए आहुति शब्द", "svadha, an ancestral oblation cry")
        member("ओम्", "ॐ, प्रणव", "om, the sacred syllable")
        member("तथा", "तथा, वैसे ही", "so, likewise")
        member("तथाहि", "क्योंकि, ऐसा ही है", "for so, because")
        member("खलु", "निश्चय ही, सचमुच", "indeed, surely")
        member("किल", "कहते हैं, सचमुच", "it is said, indeed")
        member("अथ", "अब, फिर", "now, then")
        member("सुष्टु", "भली-भाँति", "well, excellently")
        member("स्म", "था, किया करता था", "used to, did")
        member("अ", "अ ध्वनि", "the sound a")
        member("इ", "इ ध्वनि", "the sound i")
        member("उ", "उ ध्वनि", "the sound u")
        member("ऋ", "ऋ ध्वनि", "the sound r")
        member("ऌ", "ऌ ध्वनि", "the sound l")
        member("ए", "ए ध्वनि", "the sound e")
        member("ऐ", "ऐ ध्वनि", "the sound ai")
        member("ओ", "ओ ध्वनि", "the sound o")
        member("औ", "औ ध्वनि", "the sound au")
        member("आदह", "एक अव्यय निपात", "an indeclinable particle")
        member("उञ्", "एक अव्यय निपात", "an indeclinable particle")
        member("उकञ्", "एक अव्यय निपात", "an indeclinable particle")
        member("वेलायाम्", "समय पर, अवसर पर", "at the time, on the occasion")
        member("मात्रायाम्", "मात्रा में, केवल", "in measure, merely")
        member("यथा", "जैसे, जिस प्रकार", "as, just as")
        member("यत्", "जो, क्योंकि", "that which, because")
        member("तत्", "वह, इसलिए", "that, therefore")
        member("किम्", "क्या", "what, why")
        member("पुरा", "पहले, प्राचीन काल में", "formerly, before")
        member("वधा", "एक अव्यय निपात", "an indeclinable particle")
        member("वध्वा", "एक अव्यय निपात", "an indeclinable particle")
        member("धिक्", "धिक्कार", "shame on, fie")
        member("हाहा", "हाय हाय", "alas, ah")
        member("हेहै", "हे, अरे", "O, hey")
        member("हहे", "हे, अरे", "O, hey")
        member("पाट्", "ध्वनि-सूचक निपात", "an onomatopoetic particle")
        member("प्याट्", "ध्वनि-सूचक निपात", "an onomatopoetic particle")
        member("आहो", "अहो, क्या", "ah, or perhaps")
        member("उताहो", "या फिर, अथवा क्या", "or perhaps, or else")
        member("हो", "हो, हे", "ho, O")
        member("अहो", "अहो, अरे", "ah, oh")
        member("नो", "नहीं", "not")
        member("नौ", "एक अव्यय निपात", "an indeclinable particle")
        member("अथो", "और भी, फिर", "and also, then")
        member("ननु", "क्या नहीं, निश्चय ही", "is it not, surely")
        member("मन्ये", "मेरे विचार से", "I think, methinks")
        member("मिथ्या", "झूठा, व्यर्थ", "falsely, wrongly")
        member("असि", "एक अव्यय निपात", "an indeclinable particle")
        member("ब्रूहि", "कहो", "say, tell")
        member("तु", "तो, परन्तु", "but, however")
        member("नु", "क्या, अब", "now, indeed, pray")
        member("इति", "ऐसा, इस प्रकार", "thus, quotation marker")
        member("इव", "जैसे, मानो", "like, as if")
        member("वत्", "जैसा, समान", "like, similar to")
        member("वात्", "एक अव्यय निपात", "an indeclinable particle")
        member("वन", "एक अव्यय निपात", "an indeclinable particle")
        member("बत", "हाय, सचमुच", "alas, indeed")
        member("सम्", "साथ, पूर्ण रूप से", "together, completely")
        member("वशम्", "वश में", "under control")
        member("शिकम्", "एक अव्यय निपात", "an indeclinable particle")
        member("दिकम्", "एक अव्यय निपात", "an indeclinable particle")
        member("सनुकं", "एक अव्यय निपात", "an indeclinable particle")
        member("छंवट्", "एक अव्यय निपात", "an indeclinable particle")
        member("छंबट्", "एक अव्यय निपात", "an indeclinable particle")
        member("शङ्के", "शायद, मुझे संदेह है", "perhaps, I suspect")
        member("शुकम्", "एक अव्यय निपात", "an indeclinable particle")
        member("खम्", "एक अव्यय निपात", "an indeclinable particle")
        member("सनात्", "सदा से, प्राचीन काल से", "from of old, eternally")
        member("सनुतर्", "एक अव्यय निपात", "an indeclinable particle")
        member("नहिकम्", "नहीं ही", "not indeed")
        member("सत्यम्", "सचमुच, सत्य", "truly, indeed")
        member("ऋतम्", "सत्य, यथार्थ", "truthfully, rightly")
        member("अद्धा", "प्रत्यक्ष, निश्चय ही", "clearly, certainly")
        member("इद्धा", "निश्चय ही", "indeed, certainly")
        member("नोचेत्", "नहीं तो, अन्यथा", "otherwise, if not")
        member("नचेत्", "नहीं तो, अन्यथा", "otherwise, if not")
        member("नहि", "नहीं ही, क्योंकि नहीं", "not indeed, for not")
        member("जातु", "कभी, कदाचित्", "ever, at any time")
        member("कथम्", "कैसे", "how")
        member("कुतः", "कहाँ से, क्यों", "from where, why")
        member("कुत्र", "कहाँ", "where")
        member("अव", "नीचे, दूर", "down, away")
        member("अनु", "पीछे, अनुसार", "after, along, according to")
        member("हा", "हाय", "alas")
        member("हे", "हे", "O")
        member("है", "अरे, हे", "hey, O")
        member("आहोस्वित्", "या फिर, क्या", "or perhaps, whether")
        member("शम्", "कल्याण, शान्ति", "welfare, peace")
        member("कम्", "सुख, आनन्द", "happiness, pleasure")
        member("दिष्ट्या", "सौभाग्य से", "fortunately")
        member("पशु", "एक अव्यय निपात", "an indeclinable particle")
        member("नट्", "एक अव्यय निपात", "an indeclinable particle")
        member("सह", "साथ", "with, together with")
        member("आनुषट्", "यज्ञ में प्रयुक्त उद्गार", "a sacrificial exclamation")
        member("आनुषक्", "यज्ञ में प्रयुक्त उद्गार", "a sacrificial exclamation")
        member("अङ्ग", "अच्छा, अरे", "come now, well")
        member("फट्", "मन्त्र में प्रयुक्त उद्गार", "a mantra exclamation")
        member("ताजक्", "एक अव्यय निपात", "an indeclinable particle")
        member("भाजक्", "एक अव्यय निपात", "an indeclinable particle")
        member("अये", "अरे, अहो", "hey, ah")
        member("अरे", "अरे", "hey")
        member("वाट्", "एक अव्यय निपात", "an indeclinable particle")
        member("चाटु", "चापलूसी, मधुर वचन", "flattery, pleasant speech")
        member("कुम्", "एक अव्यय निपात", "an indeclinable particle")
        member("खुम्", "एक अव्यय निपात", "an indeclinable particle")
        member("घुम्", "एक अव्यय निपात", "an indeclinable particle")
        member("अम्", "अम् ध्वनि", "the sound am")
        member("ईम्", "ईम् ध्वनि", "the sound im")
        member("सीम्", "एक अव्यय निपात", "an indeclinable particle")
        member("सिम्", "एक अव्यय निपात", "an indeclinable particle")
        member("सि", "एक अव्यय निपात", "an indeclinable particle")
        member("वै", "निश्चय ही", "indeed, truly")
    },
)
