package dev.sanskrit.ganapatha

object GargadiGana : Gana(
    id = GanaIds.GARGADI,
    name = "गर्गादिः",
    sourceIndex = 59,
    sutra = "4.1.105",
    sutraId = "41105",
    sutraText = "गर्गादिभ्यो यञ्",
    sutraTransliteration = "gargaadibhyoyany",
    sutraType = "V\$\$",
    kind = GanaKind.PATHA,
    members = ganaMembers {
        member("गर्ग")
        member("वत्स")
        member("वाजासे")
        member("संकृति")
        member("अज")
        member("व्याघ्रपात्")
        member("विदभृत्")
        member("प्राचीनयोग")
        member("अगस्ति")
        member("पुलस्ति")
        member("रेभ")
        member("अग्निवेश")
        member("शङ्ख")
        member("शट")
        member("शक")
        member("एक")
        member("घूम")
        member("अवट")
        member("मनस्")
        member("धनंजय")
        member("विश्वावसु")
        member("जरमाण")
        member("लोहित")
        member("शंसित")
        member("बभ्रु")
        member("वल्गु")
        member("मण्डु")
        member("शङ्कु")
        member("लिगु")
        member("गुहलु")
        member("मन्तु")
        member("मङ्क्षु")
        member("अलिगु")
        member("जिगीषु")
        member("मनु")
        member("तन्तु")
        member("मनायीसूनु")
        member("कथक")
        member("कन्थक")
        member("ऋक्ष")
        member("तृक्ष")
        member("वृक्ष")
        member("तनु")
        member("तरुक्ष")
        member("तलुक्ष")
        member("तण्ड")
        member("वतण्ड")
        member("कपिकत")
        member("कपि")
        member("कत")
        member("कुरुकत")
        member("अनडुह्")
        member("कण्व")
        member("शकल")
        member("गोकक्ष")
        member("अगस्त्य")
        member("कण्डिनी")
        member("यज्ञवल्क")
        member("पर्णवल्क")
        member("अभयजात")
        member("विरोहित")
        member("वृषगण")
        member("रहूगण")
        member("शण्डिल")
        member("वर्णक")
        member("चणक")
        member("चुलुक")
        member("मुद्गल")
        member("मुसल")
        member("जमदग्नि")
        member("पराशर")
        member("जतूकर्ण")
        member("जातूकर्ण")
        member("महित")
        member("मन्त्रित")
        member("अश्मरथ")
        member("शर्कराक्ष")
        member("पूतिमाष")
        member("स्थूरा")
        member("अदरक")
        member("अररक")
        member("एलाक")
        member("पिङ्गल")
        member("कृष्ण")
        member("गोलन्द")
        member("उलूक")
        member("तितिक्ष")
        member("भिषज")
        member("भिषज्")
        member("भिष्णज")
        member("भडित")
        member("भण्डित")
        member("दल्भ")
        member("चेकित")
        member("चिकित्सित")
        member("देवहू")
        member("इन्द्रहू")
        member("एकलु")
        member("पिप्पलु")
        member("बृहदग्नि")
        member("सुलोहिन")
        member("सुलाभिन्")
        member("उक्थ")
        member("कुटीगु")
    },
)
