package dev.sanskrit.ganapatha

object NadadiGana : Gana(
    id = GanaIds.NADADI,
    name = "नडादिः",
    sourceIndex = 57,
    sutra = "4.1.99",
    sutraId = "41099",
    sutraText = "नडादिभ्यः फक्",
    sutraTransliteration = "nadaadibhyahaphak",
    sutraType = "V\$\$",
    kind = GanaKind.PATHA,
    notes = "Source row contains contextual annotations; only member entries are modeled here.",
    members = ganaMembers {
        member("नड")
        member("चर")
        member("वर")
        member("बक")
        member("मुञ्ज")
        member("इतिक")
        member("इतिश")
        member("उपक")
        member("एक")
        member("लमक")
        member("सप्तल")
        member("वाजप्य")
        member("तिक")
        member("प्राण")
        member("नर")
        member("सायक")
        member("दास")
        member("मित्र")
        member("द्वीप")
        member("पिङ्गर")
        member("पिङ्गल")
        member("किङ्कर")
        member("किङ्कल")
        member("कातर")
        member("कातल")
        member("काश्यप")
        member("कुश्यप")
        member("काश्य")
        member("काल्य")
        member("काव्य")
        member("अज")
        member("अमुष्य")
        member("अमुष्म")
        member("अमित्र")
        member("लिगु")
        member("चित्र")
        member("कुमार")
        member("लोह")
        member("दुर्ग")
        member("स्तम्भ")
        member("शिंशपा")
        member("अग्र")
        member("तृण")
        member("शकट")
        member("सुमनस्")
        member("सुमत")
        member("मिमत")
        member("ऋच्")
        member("जलंधर")
        member("अध्वर")
        member("युगंधर")
        member("हंसक")
        member("दण्डिन्")
        member("हस्तिन्")
        member("िण्")
        member("पञ्चाल")
        member("चमसिन्")
        member("सुकृत्य")
        member("स्थिरक")
        member("ब्राह्मण")
        member("चटक")
        member("बदर")
        member("अश्वल")
        member("खरप")
        member("लङ्क")
        member("इन्ध")
        member("अस्त्र")
        member("कामुक")
        member("व्रह्मदत्त")
        member("उदुम्बर")
        member("शोण")
        member("अलोह")
        member("दण्डप")
    },
)
