package dev.sanskrit.ganapatha

object RajadantadiGana : Gana(
    name = "राजदन्तादिः",
    sourceIndex = 17,
    sutra = "2.2.31",
    sutraId = "22031",
    sutraText = "राजदन्तादिषु परम्",
    sutraTransliteration = "raajadantaadishuparam",
    kind = GanaKind.PATHA,
    members = ganaMembers {
        member("राजदन्तः")
        member("अग्रेवणम्")
        member("लिप्तवासितम्")
        member("नग्नमुषितम्")
        member("सिक्तसंमृष्टम्")
        member("मृष्टलुञ्चितम्")
        member("अवक्लिन्नपक्वम्")
        member("अर्पितोप्तम्")
        member("उप्तगाढम्")
        member("उलूखलमुसलम्")
        member("तण्डुलकिण्वम्")
        member("दृषदुपलम्")
        member("आरड्वायनि")
        member("आरग्वायनबन्धकी")
        member("चित्ररथवाह्लीकम्")
        member("आवन्त्यश्मकम्")
        member("शूद्रार्यम्")
        member("स्नातकराजानौ")
        member("विष्वक्सेनार्जुनौ")
        member("अक्षिभ्रुवम्")
        member("दारगवम्")
        member("शब्दार्थौ")
        member("धर्मार्थौ")
        member("कामार्थौ")
        member("अर्थशब्दौ")
        member("अर्थधर्मौ")
        member("अर्थकामौ")
        member("वैकारिमतम्")
        member("गाजवाजम्")
        member("गोपालधानपूलासम्")
        member("गोपालधानीपूलासम्")
        member("पूलासकारण्डम्")
        member("पूलासककुरण्डम्")
        member("स्थूलासम")
        member("स्थूलपूलासम्")
        member("उशीरबीजम्")
        member("जिज्ञास्थि")
        member("सिञ्जास्थम्")
        member("सिञ्जाश्वत्थम्")
        member("चित्रास्वाती")
        member("चित्रस्वाती")
        member("भार्यापती")
        member("दंपती")
        member("जंपती")
        member("जायापती")
        member("पुत्रपती")
        member("पुत्रपशू")
        member("केशरश्मश्रू")
        member("शिरोबिजु")
        member("शिरोबीजम")
        member("शिरोजानु")
        member("सर्पिर्मधुन")
        member("मधुसर्पिषी")
        member("आद्यन्तौ")
        member("अन्तादी")
        member("गुणवृद्धी")
        member("वृद्धिगुणौ")
    },
)
