package dev.sanskrit.ganapatha

object ShubhradiGana : Gana(
    id = GanaIds.SHUBHRADI,
    name = "शुभ्रादिः",
    sourceIndex = 62,
    sutra = "4.1.123",
    sutraId = "41123",
    sutraText = "शुभ्रादिभ्यश्च",
    sutraTransliteration = "shubhraadibhyashcha",
    sutraType = "V\$\$",
    kind = GanaKind.AKRTI,
    members = ganaMembers {
        member("शुभ्र")
        member("विष्ट")
        member("पुर")
        member("विष्टपुर")
        member("ब्रह्मकृत")
        member("शतद्वार")
        member("शलाथल")
        member("शलाकाभ्रू")
        member("लेखाभ्रू")
        member("लेखाम्र")
        member("विकसा")
        member("विकास")
        member("रोहिणी")
        member("रुक्मिणी")
        member("धर्मिणी")
        member("दिश्")
        member("शालूक")
        member("अजबस्ति")
        member("शकंधि")
        member("विमातृ")
        member("विधवा")
        member("शुक")
        member("विश")
        member("देवतर")
        member("शकुनि")
        member("शुक")
        member("अम्र")
        member("ज्ञातल")
        member("शतल")
        member("बन्धकी")
        member("सृकण्डु")
        member("विस्रि")
        member("अतिथि")
        member("गोदन्त")
        member("कुशाम्ब")
        member("मकुण्ड")
        member("शाताहर")
        member("पवष्टुरिक")
        member("सुनामन्")
        member("लक्ष्मणश्यामयोर्वासिष्ठे")
        member("गोधा")
        member("कृकलास")
        member("अणीव")
        member("प्रवाहण")
        member("भरत")
        member("भारत")
        member("भरम")
        member("मुकण्ड")
        member("कर्पूर")
        member("इतर")
        member("अन्यतर")
        member("आलिढ")
        member("सुदन्त")
        member("सुचक्ष")
        member("सुचक्षस्")
        member("सुदामन")
        member("कद्रु")
        member("तुद")
        member("अकशाय")
        member("कुमारीका")
        member("कुठारिका")
        member("किशोरिका")
        member("अम्बिका")
        member("जिह्माशिन्")
        member("परिधि")
        member("वायुदत्त")
        member("शकल")
        member("शलाका")
        member("खडूर")
        member("कुबेरिका")
        member("अशोका")
        member("गन्धपिङ्गला")
        member("खडोन्मत्ता")
        member("अनुदृष्टिन्")
        member("अनुदृष्टि")
        member("जरतिन्")
        member("बलीवर्दिन्")
        member("विप्र")
        member("वीज")
        member("जीव")
        member("श्वन")
        member("अश्मन्")
        member("अश्व")
        member("अजिर")
    },
)
