package dev.panini.ashtadhyayi.adhyaya2.pada1

import dev.panini.sutra.Sutra

object Adhyaya2Pada1 {
    val sutras: List<Sutra<*, *>> = listOf(
        AvyayamVibhaktiSutra,
        ApapariBahirAncavahPancamyaSutra,
        AngMaryadabhividhyohSutra,
        LaksanenAbhipratiAbhimukhyeSutra,
        PareMadhyeShashthyaVaSutra,
        SankhyaVamsyenaSutra,
        AnyapadartheChaSutra,
        DvitIyaSritatitapatitagatatyastapraptapannaihSutra,
        KalaAtyantasamyogeSutra,
        TrtiyaTatkrtarthenaGunavacanenaSutra,
        KartrkaraneKrtaBahulamSutra,
        AnnasenaVyanjanamSutra,
        CaturthiTadarthartheSutra,
        PancamiBhayenaSutra,
        StokantikadharthaniPancamyaSutra,
        ApetaApodhaMuktaSutra,
        SaptamiSaundaihSutra,
        SiddhasuskapakvabandhaishchaSutra,
        SankhyapurvoDviguhSutra,
        UpamananiSamanyavacanaihSutra,
        UpamitamVyaghradibhihSutra,
        VisesanamVisesyenaBahulamSutra,
        PurvakaladiSutra,
        SrenyadayahKrtadibhihSutra,
        KtenaNanjVisistenaSutra,
        SanMahatParamottamaSutra,
        PapakeKutsitaihsutra,
        KumarahShramanadibhihSutra,
        ChatuspadoGarbhinyaSutra,
        PurvaSadrshaSamonarthaKalahaNipunaMishraSlaksnaihSutra,
        KrtyairRneSutra,
        TaddhitarthaUttarapadaSamahareChaSutra,
        KataraKatambhauJatipraparishneSutra,
        PrasamsavacanaiscaSutra,
        SvayamKretenaSutra,
        BhaksyenaMishrikaranamSutra,
        YuvaKhalatiPalitaSutra,
        MayuravyamsakadayascaSutra,
        KutsitaniKutsitaihSutra,
        KhatvaKsepeSutra,
        SamiSutra,
        KsepePrasamsayamChaSutra,
        YathaSadrshyeSutra,
        AnurYatSamayaSutra,
        YasyaChayamahSutra,
        AtyantaSamyogeChaSutra,
    )
}
