package dev.sanskrit.dhatupatha

/** Complete Kryadi-gaṇa imported from the MIT-shared ashtadhyayi-com data set. */
object KryadiDhatus {
    val all: List<Dhatu> = dhatuPatha(Gana.KRYADI) {
        dhatu("09.0001", 1, "डुक्रीञ्", "द्रव्यविनिमये", "खरीदना, बदले में लेना", "to buy, to purchase", PadaType.UBHAYAPADA)
        dhatu("09.0002", 2, "प्रीञ्", "तर्पणे कान्तौ च", "प्रीती करना, तृप्त करना, कामना करना", "to love, to satisfy, to wish, to desire, to show kindness", PadaType.UBHAYAPADA)
        dhatu("09.0003", 3, "श्रीञ्", "पाके", "पकाना", "to cook", PadaType.UBHAYAPADA)
        dhatu("09.0004", 4, "मीञ्", "हिंसायाम्", "बाँधना, मार डालना या दुःख देना", "to tie, to bind, to kill, to destroy, to hurt", PadaType.UBHAYAPADA)
        dhatu("09.0005", 5, "षिञ्", "बन्धने", "बांधना, गूंथना, फन्दे से पकड़ना", "to tie, to bind, to string, to catch with a stick", PadaType.UBHAYAPADA)
        dhatu("09.0006", 6, "स्कुञ्", "आप्रवणे", "कूदना, फुदकना, ऊपर उठाना, उड़ाना, आच्छादित करना, ढकना", "to jump, to leap, to make something fly, to pull up, to cover", PadaType.UBHAYAPADA)
        dhatu("09.0007", 7, "स्तन्भुँ", "रोधने स्तम्भने च", "", "to stop,to hinder,to become stiff, to obstruct", PadaType.PARASMAIPADA)
        dhatu("09.0008", 8, "स्तुन्भुँ", "रोधने निष्कोषणे च", "", "to stop,to hinder,to become stiff, to obstruct", PadaType.PARASMAIPADA)
        dhatu("09.0009", 9, "स्कन्भुँ", "रोधने स्तम्भने च", "", "to stop,to hinder,to become stiff, to obstruct", PadaType.PARASMAIPADA)
        dhatu("09.0010", 10, "स्कुन्भुँ", "रोधने धारणे च", "", "to stop,to hinder,to become stiff, to obstruct", PadaType.PARASMAIPADA)
        dhatu("09.0011", 11, "युञ्", "बन्धने", "बांधना", "to tie, to bind", PadaType.UBHAYAPADA)
        dhatu("09.0012", 12, "क्नूञ्", "शब्दे", "शब्द करना, आवाज करना", "to sound", PadaType.UBHAYAPADA)
        dhatu("09.0013", 13, "द्रूञ्", "हिंसायाम्", "हिंसा करना, मार डालना", "to kill, to destroy", PadaType.UBHAYAPADA)
        dhatu("09.0014", 14, "पूञ्", "पवने", "पवित्र करना, स्वच्छ करना", "to purify, to cleanse", PadaType.UBHAYAPADA)
        dhatu("09.0015", 15, "शॄञ्", "हिंसायाम्", "हिंसा करना, मार डालना", "to kill, to destroy", PadaType.UBHAYAPADA)
        dhatu("09.0016", 16, "लूञ्", "छेदने", "कतरना, काटना, चीरना", "to cut, to pluck, to destroy, to dissolve", PadaType.UBHAYAPADA)
        dhatu("09.0017", 17, "स्तॄञ्", "आच्छादने", "वस्त्रादि से आच्छादित करना, वस्त्र ओढ़ाना", "to wrap, to cover, to clothe", PadaType.UBHAYAPADA)
        dhatu("09.0018", 18, "कॄञ्", "हिंसायाम्", "हिंसा करना, मार डालना", "to kill, to destroy", PadaType.UBHAYAPADA)
        dhatu("09.0019", 19, "वॄञ्", "वरणे", "पसन्द करना, स्वीकार करना", "to marry, to accept, to own, to choose", PadaType.UBHAYAPADA)
        dhatu("09.0020", 20, "धूञ्", "कम्पने", "कम्पित करना, हिलाना, क्षोभित करना", "to shake,to agitate, to tremble, to cause to shake, to cause to agigate, to tremble", PadaType.UBHAYAPADA)
        dhatu("09.0021", 21, "शॄ", "हिंसायाम्", "हिंसा करना, मार डालना", "to kill, to destroy", PadaType.PARASMAIPADA)
        dhatu("09.0022", 22, "पॄ", "पालनपूरणयोः", "पालन करना, पूर्ति करना, पूर्ण करना, भरना", "to protect, to take care, to nurture, to complete, to fill, to fulfill", PadaType.PARASMAIPADA)
        dhatu("09.0023", 23, "वॄ", "वरणे", "वरण करना, पसन्द करना, आश्रय देना, संभालना", "to marry, to accept, to own, to choose", PadaType.PARASMAIPADA)
        dhatu("09.0024", 24, "भॄ", "भर्त्सने", "घुड़कना, तिरस्कार करना, संरक्षण करना, पालन करना, धारण करना", "to hate, to insult", PadaType.PARASMAIPADA)
        dhatu("09.0025", 25, "मॄ", "हिंसायाम्", "मार डालना या दुःख देना", "to kill, to destroy, to hurt", PadaType.PARASMAIPADA)
        dhatu("09.0026", 26, "दॄ", "विदारणे", "चीरना, फाड़ना, टुकड़े टुकड़े करना", "to break apart, to tear off, to cut", PadaType.PARASMAIPADA)
        dhatu("09.0027", 27, "जॄ", "वयोहानौ", "जीर्ण होना, वृद्ध होना", "to grow old", PadaType.PARASMAIPADA)
        dhatu("09.0028", 28, "झॄ", "वयोहानौ", "", "to grow old", PadaType.PARASMAIPADA)
        dhatu("09.0029", 29, "धॄ", "वयोहानौ", "", "", PadaType.PARASMAIPADA)
        dhatu("09.0030", 30, "नॄ", "नये", "ले जाना", "to take away, to carry", PadaType.PARASMAIPADA)
        dhatu("09.0031", 31, "कॄ", "हिंसायाम्", "मारना, मार डालना, दुःख देना", "to kill, to destroy", PadaType.PARASMAIPADA)
        dhatu("09.0032", 32, "ॠ", "गतौ", "जाना", "to go", PadaType.PARASMAIPADA)
        dhatu("09.0033", 33, "गॄ", "शब्दे", "शब्द करना", "to sound, to talk", PadaType.PARASMAIPADA)
        dhatu("09.0034", 34, "ज्या", "वयोहानौ", "वृद्ध होना, जीर्ण होना, पुराना होना", "to become old,to decay", PadaType.PARASMAIPADA)
        dhatu("09.0035", 35, "री", "गतिरेषणयोः", "जाना, शिशुप्राणी के समान पुकारना, पीड़ा करना, दुःख देना, मारना", "to go, to howl, to kill, to destroy, to hurt", PadaType.PARASMAIPADA)
        dhatu("09.0036", 36, "ली", "श्लेषणे", "युक्त होना, प्राप्त होना, मिलना", "to adhere to, to be absorbed,to get dissolved", PadaType.PARASMAIPADA)
        dhatu("09.0037", 37, "व्ली", "वरणे", "पसंद करना, ढूंढ निकालना, बीनना", "to choose,to select,to find, to marry, to cover, to glean", PadaType.PARASMAIPADA)
        dhatu("09.0038", 38, "ब्ली", "वरणे", "", "to choose,to select,to find, to marry, to cover, to glean", PadaType.PARASMAIPADA)
        dhatu("09.0039", 39, "प्ली", "गतौ", "जाना", "to go", PadaType.PARASMAIPADA)
        dhatu("09.0040", 40, "व्री", "वरणे", "वरण करना, चुनना, ढूंढकर निकालना, पसन्द करना, बीनना", "to choose,to select,to find, to marry, to cover, to glean", PadaType.PARASMAIPADA)
        dhatu("09.0041", 41, "भ्री", "भये", "डरना, धारण करना, आश्रय देना, पालन करना", "to fear,to support, to wear, to obey", PadaType.PARASMAIPADA)
        dhatu("09.0042", 42, "क्षीष्", "हिंसायाम्", "दुःख देना, पीड़ा देना, मार डालना", "to kill, to destroy, to cause pain, to hurt", PadaType.PARASMAIPADA)
        dhatu("09.0043", 43, "ज्ञा", "अवबोधने", "जानना, समझना", "to know, to realize, to understand", PadaType.PARASMAIPADA)
        dhatu("09.0044", 44, "बन्धँ", "बन्धने", "बांधना", "to tie, to bind", PadaType.PARASMAIPADA)
        dhatu("09.0045", 45, "वृङ्", "सम्भक्तौ", "सेवा करना, परिश्चर्या करना", "to serve, to worship, to care", PadaType.ATMANEPADA)
        dhatu("09.0046", 46, "श्रन्थँ", "विमोचनप्रतिहर्षयोः", "त्याग करना, विमोचन करना, आनन्द करना", "to leave, to liberate, to set free, to be happy", PadaType.PARASMAIPADA)
        dhatu("09.0047", 47, "मन्थँ", "विलोडने", "विलोना, मथना", "to churn,to shake,to agitate", PadaType.PARASMAIPADA)
        dhatu("09.0048", 48, "श्रन्थँ", "सन्दर्भे", "रचना करना, क्रम से रखना", "to arrange, to put in sequence", PadaType.PARASMAIPADA)
        dhatu("09.0049", 49, "ग्रन्थँ", "सन्दर्भे", "ग्रन्थ लिखना, सन्दर्भ लगाना", "to arrange, to put in sequence", PadaType.PARASMAIPADA)
        dhatu("09.0050", 50, "कुन्थँ", "संश्लेषणे", "मिलकर रहना", "to stay together", PadaType.PARASMAIPADA)
        dhatu("09.0051", 51, "मृदँ", "क्षोदे", "पीसना, कूटना, चूर्ण करना, मर्दन करना", "to powder, to cut, to grind", PadaType.PARASMAIPADA)
        dhatu("09.0052", 52, "मृडँ", "क्षोदे सुखे च", "चूर्ण करना, कूटना, सुख देना", "to powder, to cut, to grind, to make happy", PadaType.PARASMAIPADA)
        dhatu("09.0053", 53, "गुधँ", "रोषे", "क्रोध करना", "to be angry", PadaType.PARASMAIPADA)
        dhatu("09.0054", 54, "कुषँ", "निष्कर्षे", "बाहर निकालना, रगड़ के निकालना, कसौटी पर घिसके सोने आदि की परीक्षा करना", "to take out, to extract, to examine a metal, to investigate purity of a metal", PadaType.PARASMAIPADA)
        dhatu("09.0055", 55, "क्षुभँ", "सञ्चलने", "मथना", "to tremble, to shake, to agitate", PadaType.PARASMAIPADA)
        dhatu("09.0056", 56, "णभँ", "हिंसायाम्", "मार डालना", "to kill, to destroy", PadaType.PARASMAIPADA)
        dhatu("09.0057", 57, "तुभँ", "हिंसायाम्", "मार डालना", "to kill, to detroy", PadaType.PARASMAIPADA)
        dhatu("09.0058", 58, "क्लिशूँ", "विबाधने", "क्लेश या दुःख देना, हरकत करना, दुःख सहन करना", "to torment, to distress, to hurt, to suffer, to misbehave", PadaType.PARASMAIPADA)
        dhatu("09.0059", 59, "अशँ", "भोजने", "खाना, भोजन करना", "to eat, to consume", PadaType.PARASMAIPADA)
        dhatu("09.0060", 60, "उँध्रसँ", "उञ्छे", "बीनना, एक एक करके चुनना, ऊपर फेंकना, उडा देना", "to gather, to pick, to glean", PadaType.PARASMAIPADA)
        dhatu("09.0061", 61, "इषँ", "आभीक्ष्ण्ये", "बार बार करना", "to repeat", PadaType.PARASMAIPADA)
        dhatu("09.0062", 62, "विषँ", "विप्रयोगे", "उपयोग न होने से अलग करना या निकाल देना", "to remove, to throw away, to separate the undesired part", PadaType.PARASMAIPADA)
        dhatu("09.0063", 63, "प्रुषँ", "स्नेहनसेवनपूरणेषु", "सौम्य होना, स्निग्ध होना, चिकना होना, सींचना, पूर्ण करना, भरना", "to soften, to be greasy, to irrigate, to complete, to fill", PadaType.PARASMAIPADA)
        dhatu("09.0064", 64, "प्लुषँ", "स्नेहनसेवनपूरणेषु", "सौम्य होना, स्निग्ध होना, चिकना होना, सींचना, पूर्ण करना, भरना", "to soften, to be greasy, to irrigate, to complete, to fill", PadaType.PARASMAIPADA)
        dhatu("09.0065", 65, "पुषँ", "पुष्टौ", "पालन करना, पोषण करना", "to nourish,to bring up,to support", PadaType.PARASMAIPADA)
        dhatu("09.0066", 66, "मुषँ", "स्तेये", "चुराना, चोरी करना", "to steal", PadaType.PARASMAIPADA)
        dhatu("09.0067", 67, "खचँ", "भूतप्रादुर्भावे", "मर्यादा होने पर भी देर से जन्म लेना, संपत्ति युक्त करना, स्वेच्छया पवित्र करना", "to occur in abundance", PadaType.PARASMAIPADA)
        dhatu("09.0068", 68, "खवँ", "भूतप्रादुर्भावे", "", "to occur in abundance", PadaType.PARASMAIPADA)
        dhatu("09.0069", 69, "हेठँ", "भूतप्रादुर्भावे", "मर्यादा होने पर भी देर से जन्म लेना, संपत्ति युक्त करना, स्वेच्छया पवित्र करना", "to occur in abundance", PadaType.PARASMAIPADA)
        dhatu("09.0070", 70, "स्वॄ", "वरणे", "वरण करना, पसन्द करना, आश्रय देना, संभालना", "to marry, to accept, to own, to choose", PadaType.PARASMAIPADA)
        dhatu("09.0071", 71, "ग्रहँ", "उपादाने", "लेना, स्वीकार करना", "to take, to accept, to obtain", PadaType.UBHAYAPADA)
    }
}
