package dev.sanskrit.dhatupatha

/** Complete Svadi-gaṇa imported from the MIT-shared ashtadhyayi-com data set. */
object SvadiDhatus {
    val all: List<Dhatu> = dhatuPatha(Gana.SVADI) {
        dhatu("05.0001", 1, "षुञ्", "अभिषवे", "स्नान करना, यंत्रादि द्वारा अर्क निकालना, मथना, मद्य चुआना", "to bathe, to extract, to distill, to juice, to agitate, to churn", PadaType.UBHAYAPADA)
        dhatu("05.0002", 2, "षिञ्", "बन्धने", "बांधना, गूंथना", "to tie,to bind, to quill, to interlock", PadaType.UBHAYAPADA)
        dhatu("05.0003", 3, "शिञ्", "निशाने", "तीक्ष्ण करना, पैना करना, पतला करना", "to sharpen, to whet", PadaType.UBHAYAPADA)
        dhatu("05.0004", 4, "डुमिञ्", "प्रक्षेपणे", "फेंकना, फैलाना", "to throw,to scatter", PadaType.UBHAYAPADA)
        dhatu("05.0005", 5, "चिञ्", "चयने", "चुनना, बटोरना, एकत्र करना", "to collect, to select, to pick", PadaType.UBHAYAPADA)
        dhatu("05.0006", 6, "स्तृञ्", "आच्छादने", "आच्छादित करना, ढकना, फैलाना, विस्तार होना या करना, बिछाना", "to cover,to eclipse, to spread, to expand", PadaType.UBHAYAPADA)
        dhatu("05.0007", 7, "कृञ्", "हिंसायाम्", "मार डालना, दुःख देना, सताना", "to kill, to destroy, to irritate", PadaType.UBHAYAPADA)
        dhatu("05.0008", 8, "वृञ्", "वरणे", "पसंद करना, नियोजित करना, नियमित करना", "to choose,to select,to marry,to finalize", PadaType.UBHAYAPADA)
        dhatu("05.0009", 9, "धुञ्", "कम्पने", "कांपना, हिलना", "to shake,to tremble", PadaType.UBHAYAPADA)
        dhatu("05.0010", 10, "धूञ्", "कम्पने", "", "to shake,to tremble", PadaType.UBHAYAPADA)
        dhatu("05.0011", 11, "टुदु", "उपतापे", "दुःख देना, जलना, तप्त करना, जलाना", "to give pain,to burn,to heat, to set on fire", PadaType.PARASMAIPADA)
        dhatu("05.0012", 12, "हि", "गतौ वृद्धौ च", "जाना, बढ़ना", "to go,to grow", PadaType.PARASMAIPADA)
        dhatu("05.0013", 13, "पृ", "प्रीतौ", "तृप्त करना, संतुष्ट करना", "to satisfy, to please", PadaType.PARASMAIPADA)
        dhatu("05.0014", 14, "स्पृ", "प्रीतिपालनयोः प्रीतिचलनयोश्च", "सन्तुष्ट करना, प्रसन्न करना, पालन करना, जाना", "to satisfy, to please, to nurture, to nourish, to go", PadaType.PARASMAIPADA)
        dhatu("05.0015", 15, "स्मृ", "प्रीतिबलनयोः", "", "to satisfy, to please, to force", PadaType.PARASMAIPADA)
        dhatu("05.0016", 16, "आपॢँ", "व्याप्तौ", "व्याप्त होना, व्यापना", "to obtain,to pervade,to occupy,to reach, to get", PadaType.PARASMAIPADA)
        dhatu("05.0017", 17, "शकॢँ", "शक्तौ", "शक्तिवान होना, समर्थ होना, शकना", "to be able,to be powerful", PadaType.PARASMAIPADA)
        dhatu("05.0018", 18, "राधँ", "संसिद्धौ", "पूरा करना, सिद्ध करना", "to accomplish, to attain, to fulfill, to achieve", PadaType.PARASMAIPADA)
        dhatu("05.0019", 19, "साधँ", "संसिद्धौ", "सिद्ध करना, जय पाना, साधना करना", "to accomplish, to attain, to fulfill,  to achieve", PadaType.PARASMAIPADA)
        dhatu("05.0020", 20, "अशूँ", "व्याप्तौ सङ्घाते च", "फैलना, राशि करना, ढेर करना", "to pervade,to heap,to pile up", PadaType.ATMANEPADA)
        dhatu("05.0021", 21, "ष्टिघँ", "आस्कन्दने", "हल्ला करना, तिरस्कार करना, वध करना", "to attack, to hate, to kill, to destroy", PadaType.ATMANEPADA)
        dhatu("05.0022", 22, "तिकँ", "आस्कन्दने गतौ च", "तिरस्कार करना, वध करना, जाना", "to attack, to hate, to kill, to destroy, to go", PadaType.PARASMAIPADA)
        dhatu("05.0023", 23, "तिगँ", "आस्कन्दने गतौ च", "तिरस्कार करना, वध करना, जाना", "to attack, to hate, to kill, to destroy, to go", PadaType.PARASMAIPADA)
        dhatu("05.0024", 24, "षघँ", "हिंसायाम्", "मारना, हिंसा करना", "to kill, to destroy", PadaType.PARASMAIPADA)
        dhatu("05.0025", 25, "ञिधृषाँ", "प्रागल्भ्ये", "गर्व करना, अपने को बड़ा समझना", "to boast, to be proud, to show off", PadaType.PARASMAIPADA)
        dhatu("05.0026", 26, "दन्भुँ", "दम्भने", "ठगना, वंचना करना", "to deceive,to cheat", PadaType.PARASMAIPADA)
        dhatu("05.0027", 27, "ऋधुँ", "वृद्धौ", "बढ़ना", "to increase,to prosper", PadaType.PARASMAIPADA)
        dhatu("05.0028", 28, "तृपँ", "प्रीणने", "", "to satisfy, to please", PadaType.PARASMAIPADA)
        dhatu("05.0029", 29, "अहँ", "व्याप्तौ", "फैलना, विस्तृत होना", "to pervade, to expand, to spread", PadaType.PARASMAIPADA)
        dhatu("05.0030", 30, "दघँ", "घातने पालने च", "मारना, दुःख देना, संरक्षण करना, पोषण करना", "to kill, to destroy, to protect", PadaType.PARASMAIPADA)
        dhatu("05.0031", 31, "चमुँ", "भक्षणे", "खाना", "to eat,to drink", PadaType.PARASMAIPADA)
        dhatu("05.0032", 32, "रि", "हिंसायाम्", "मारना, हिंसा करना", "to kill, to destroy, to damage, to hurt", PadaType.PARASMAIPADA)
        dhatu("05.0033", 33, "क्षि", "हिंसायाम्", "मारना, हिंसा करना", "to kill, to destroy, to damage, to hurt", PadaType.PARASMAIPADA)
        dhatu("05.0034", 34, "चिरि", "हिंसायाम्", "मारना, हिंसा करना", "to kill, to destroy, to damage, to hurt", PadaType.PARASMAIPADA)
        dhatu("05.0035", 35, "जिरि", "हिंसायाम्", "मारना, हिंसा करना", "to kill, to destroy, to damage, to hurt", PadaType.PARASMAIPADA)
        dhatu("05.0036", 36, "दाशँ", "हिंसायाम्", "मारना, हिंसा करना", "to kill, to destroy, to damage, to hurt", PadaType.PARASMAIPADA)
        dhatu("05.0037", 37, "दृ", "हिंसायाम्", "मारना, हिंसा करना", "to kill, to destroy, to damage, to hurt", PadaType.PARASMAIPADA)
        dhatu("05.0038", 38, "ऋक्षि", "हिंसायाम्", "", "to kill, to destroy, to damage, to hurt", PadaType.PARASMAIPADA)
    }
}
