package dev.panini.ashtadhyayi.adhyaya1.pada4

import dev.panini.sutra.Sutra

object Adhyaya1Pada4 {
    val sutras: List<Sutra<*, *>> = listOf(
        AkadaradEkaSamjnaSutra,
        KarakeSutra,
        YasmatPratyayaVidhiSutra,
        YaciBhamSutra,
        ViramoAvasanamSutra,
        SuptingantamPadamSutra,
        GhiSutra,
        NadiSutra,
        ChadayoAsattveSutra,
        PradayaSutra,
        UpasargahKriyayogeSutra,
        GatishCaSutra,
        UryadiCvidacashCaSutra,
        SakshatPrabhrtiniCaSutra,
        DhruvamApayeApadanamSutra,
        KarmanaYamAbhipraitiSampradanamSutra,
        SadhakatamamKaranamSutra,
        BhuvahPrabhavahSutra,
        AdhishingsthasamKarmaSutra,
        JanikartuhPrakrtihSutra,
        KrudhaDruhersyasuyarthanamYamPratiKopahSutra,
        RadhiksyorYasyaViprasnahSutra,
        BhitharthanamBhayahetuhSutra,
        RucyarthanamPriyamanahSutra,
        KrudhaDruhorUpasrstayohKarmaSutra,
        YenangavikarahKaranaSutra,
        UpanvadhyangvasahSutra,
        ParajerasodhahSutra,
        AkhyatopayogeSutra,
        SprherIpsitahSutra,
        AbhinivishasCaSutra,
        VaranarthanamIpsitahSutra,
        AntardhauYenadarsanamIcchatiSutra,
        DharerUttamarnahSutra,
        ShlaghahnusthashapamJnyipsyamanahSutra,
        DivahKarmaCaSutra,
        ParikrayaneSampradanamAnyatarasyamSutra,
        PratyangbhruvahPurvasyaKartaSutra,
        AnupratigrnasCaSutra,
        TathayuktamCanipsitamSutra,
    )
}
