package dev.panini.compiler

import dev.panini.execution.SanskritValue
import dev.panini.shiksha.Samjna
import org.objectweb.asm.ClassWriter
import org.objectweb.asm.Opcodes.ACC_PUBLIC
import org.objectweb.asm.Opcodes.ACC_STATIC
import org.objectweb.asm.Opcodes.ARETURN
import org.objectweb.asm.Opcodes.V17
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs

class StructuredValueBytecodeEmitterTest {
    @Test
    fun `complete recursive value hierarchy round trips through generated bytecode`() {
        val expected = SanskritValue.Rupa(
            schema = "परीक्षा",
            fields = linkedMapOf(
                "सूची" to SanskritValue.Suchi(
                    listOf(
                        SanskritValue.Sankhya(2L, "द्वे"),
                        SanskritValue.Gana(
                            listOf(
                                SanskritValue.Range(
                                    SanskritValue.Sankhya(1L, "एक"),
                                    SanskritValue.Sankhya(3L, "त्रि"),
                                ),
                                SanskritValue.Rational(1L, 2L, "अर्धम्"),
                            ),
                        ),
                        SanskritValue.Satya(true, "सत्यविशेषः"),
                        SanskritValue.Shabda(
                            "सत्यम्",
                            setOf(Samjna.SHABDA, Samjna.GANA, Samjna.Rudhi("विशेषः")),
                        ),
                        SanskritValue.Lopa,
                    ),
                ),
                "असत्यम्" to SanskritValue.Satya(false),
            ),
        )
        val className = "CompiledStructuredValueRoundTrip"
        val writer = ClassWriter(ClassWriter.COMPUTE_FRAMES or ClassWriter.COMPUTE_MAXS)
        writer.visit(V17, ACC_PUBLIC, className, null, "java/lang/Object", null)
        val method = writer.visitMethod(
            ACC_PUBLIC or ACC_STATIC,
            "value",
            "()Ldev/panini/execution/SanskritValue;",
            null,
            null,
        )
        method.visitCode()
        StructuredValueBytecodeEmitter.emit(method, expected)
        method.visitInsn(ARETURN)
        method.visitMaxs(0, 0)
        method.visitEnd()
        writer.visitEnd()

        val bytes = GeneratedBytecodeVerifier.verify(writer.toByteArray())
        val generated = BytecodeCompiler.PaniniClassLoader(javaClass.classLoader)
            .loadFromBytes(className, bytes)
        val actual = generated.getMethod("value").invoke(null) as SanskritValue

        assertEquals(expected, actual)
        val literalTruth = (((actual as SanskritValue.Rupa).fields.getValue("सूची") as SanskritValue.Suchi)
            .items[3])
        assertIs<SanskritValue.Shabda>(literalTruth)
        assertEquals(setOf(Samjna.SHABDA, Samjna.GANA, Samjna.Rudhi("विशेषः")), literalTruth.samjnas)
    }
}
