package dev.panini.ashtadhyayi.adhyaya2.pada3

import dev.panini.sutra.Sutra

object Adhyaya2Pada3 {
    val sutras: List<Sutra<*, *>> = listOf(
        AnabhihiteSutra,
        KarmaniDvitiyaSutra,
        AntarantarenaYukteSutra,
        KaladhvanorAtyantasamyogeSutra,
        KarmapravacaniyayukteDvitiyaSutra,
        EnapaDvitiyaSutra,
        PancamyApangParibhihSutra,
        PratinidhiPratidaneCaYasmatSutra,
        GatyarthaKarmaniDvitiyaCaturthyauSutra,
        ChaturthiSampradaneSutra,
        KriyarthopapadasyaCaKarmaniSthaninahSutra,
        TumarthacCaBhavavacanatSutra,
        NamahSvastiSvahaSutra,
        ManyaKarmaniAnadareSutra,
        KartrkaranayostrtiyaSutra,
        SahaYukteApradhaneSutra,
        YenangavikarahSutra,
        ItthambhutalaksaneSutra,
        HetauSutra,
        VibhasaGuneAstriyamSutra,
        SasthiHetuprayogeSutra,
        SarvanamnasTrtiyaCaSutra,
        ApadanePancamiSutra,
        AnyaraditarartedikshabdaSutra,
        SasthyAtasarthaPratyayenaSutra,
        PrthagVinaNanabhihSutra,
        DurantikarthebhyoDvitiyaCaSutra,
        SaptamyAdhikaraneCaSutra,
        YasyaCaBhavenaBhavalaksanamSutra,
        SasthiCanadareSutra,
        SwamyIsvaraAdhipatiSutra,
        AyuktaKusalabhyamCaSevayamSutra,
        YatasCaNirdharanamSutra,
        PancamiVibhakteSutra,
        SadhuNipunabhyamSutra,
        PrasitotsukabhyamTrtiyaCaSutra,
        PratipadikarthalingaparimanavacanamatrePrathamaSutra,
        SambodhaneCaSutra,
        SasthiSeseSutra,
        JnyoAvidarthasyaKaraneSutra,
        AdhigarthaDayesamKarmaniSutra,
        KartrKarmanohKrtiSutra,
        NaLokavyayanisthanisthakhalarthatrnnamSutra,
        KasyaCaVartamaneSutra,
        KrtyanamKartariVaSutra,
        TulyarthairAtulopamabhyamTrtiyanatarasyamSutra,
        CaturthyAsisyAyusyamadraBhadraKusalaSukharthaHitaihSutra,
    )
}
