package dev.panini.ashtadhyayi.adhyaya5.pada4

object AngulerDaruniSutra : CanonicalInactiveSamasaSutra(114, "अङ्गुलेर्दारुणि")
object DvitribhyamSaMurdhnahSutra : CanonicalInactiveSamasaSutra(115, "द्वित्रिभ्यां ष मूर्ध्नः")
object ApPuraniPramanyohSutra : CanonicalInactiveSamasaSutra(116, "अप् पूरणीप्रमाण्योः")
object AntarbahirbhyamCaLomnahSutra : CanonicalInactiveSamasaSutra(117, "अन्तर्बहिर्भ्यां च लोम्नः")
object AnNasikayahSamjnayamNasamCasthulatSutra : CanonicalInactiveSamasaSutra(118, "अञ्नासिकायाः संज्ञायां नसं चास्थूलात्")
object UpasargacCaSutra : CanonicalInactiveSamasaSutra(119, "उपसर्गाच्च")
object SupratasusvasudivaCanonicalSutra : CanonicalInactiveSamasaSutra(120, "सुप्रातसुश्वसुदिवशारिकुक्षचतुरश्रैणीपदाजपदप्रोष्ठपदाः")
object NanjDuhSubhyoHalisakthyorAnyatarasyamSutra : CanonicalInactiveSamasaSutra(121, "नञ्दुःसुभ्यो हलिसक्थ्योरन्यतरस्याम्")
object NityamAsicPrajaMedhayohSutra : CanonicalInactiveSamasaSutra(122, "नित्यमसिच् प्रजामेधयोः")
object BahuprajasChandasiSutra : CanonicalInactiveSamasaSutra(123, "बहुप्रजाश्छन्दसि")
object DharmadAnicKevalatSutra : CanonicalInactiveSamasaSutra(124, "धर्मादनिच् केवलात्")
object JambhaSuharitaTrnaSomebhyahSutra : CanonicalInactiveSamasaSutra(125, "जम्भा सुहरिततृणसोमेभ्यः")
object DaksinerMaLubdhayogeSutra : CanonicalInactiveSamasaSutra(126, "दक्षिणेर्मा लुब्धयोगे")
object IcKarmavyatihareSutra : CanonicalInactiveSamasaSutra(127, "इच् कर्मव्यतिहारे")
object DvidandyadibhyasCaSutra : CanonicalInactiveSamasaSutra(128, "द्विदण्ड्यादिभ्यश्च")
object PrasambhyamJanunorJnuhSutra : CanonicalInactiveSamasaSutra(129, "प्रसम्भ्यां जानुनोर्ज्ञुः")
object UrdhvadVibhasaSutra : CanonicalInactiveSamasaSutra(130, "ऊर्ध्वाद्विभाषा")
object UdhasoAnanSutra : CanonicalInactiveSamasaSutra(131, "ऊधसोऽनङ्")
object DhanusasCaSutra : CanonicalInactiveSamasaSutra(132, "धनुषश्च")
object VaSamjnayamSutra : CanonicalInactiveSamasaSutra(133, "वा संज्ञायाम्")
object JayayaNinSutra : CanonicalInactiveSamasaSutra(134, "जायाया निङ्")
object GandhasyedutputisusurabhibhyahSutra : CanonicalInactiveSamasaSutra(135, "गन्धस्येदुत्पूतिसुसुरभिभ्यः")
object AlpakhyayamSutra : CanonicalInactiveSamasaSutra(136, "अल्पाख्यायाम्")
object UpamanacCaSutra : CanonicalInactiveSamasaSutra(137, "उपमानाच्च")
object PadasyaLopoAhastyadibhyahSutra : CanonicalInactiveSamasaSutra(138, "पादस्य लोपोऽहस्त्यादिभ्यः")
object KumbhapadisuCaSutra : CanonicalInactiveSamasaSutra(139, "कुम्भपदीषु च")
object SankhyasupurvasyaSutra : CanonicalInactiveSamasaSutra(140, "संख्यासुपूर्वस्य")
object VayasiDantasyaDatruSutra : CanonicalInactiveSamasaSutra(141, "वयसि दन्तस्य दतृ")
object ChandasiCaSutra : CanonicalInactiveSamasaSutra(142, "छन्दसि च")
object StriyamSamjnayamSutra : CanonicalInactiveSamasaSutra(143, "स्त्रियां संज्ञायाम्")
object VibhasaSyavarokabhyamSutra : CanonicalInactiveSamasaSutra(144, "विभाषा श्यावारोकाभ्याम्")
object AgrantasuddhasubhravrsavarahebhyasCaSutra : CanonicalInactiveSamasaSutra(145, "अग्रान्तशुद्धशुभ्रवृषवराहेभ्यश्च")
object KakudasyavasthayamLopahSutra : CanonicalInactiveSamasaSutra(146, "ककुदस्यावस्थायां लोपः")
object TrikakutParvateSutra : CanonicalInactiveSamasaSutra(147, "त्रिककुत् पर्वते")
object UdvibhyamKakudasyaSutra : CanonicalInactiveSamasaSutra(148, "उद्विभ्यां काकुदस्य")
object PurnadVibhasaSutra : CanonicalInactiveSamasaSutra(149, "पूर्णाद्विभाषा")
