package dev.panini.ashtadhyayi.adhyaya5.pada4

import dev.panini.analysis.*
import dev.panini.core.*
import dev.panini.shiksha.Samjna

private fun members(c:SamasaRuleContext)=c.padas.joinToString(""){it.upadesha}
private fun leading(c:SamasaRuleContext)=c.padas.dropLast(1).joinToString(""){it.upadesha}
private fun finalAsA(c:SamasaRuleContext):String { val u=c.uttaraPada.upadesha; val x=when(u){"गो"->"गव";"नौ","नाव"->"नाव";"अक्षि"->"अक्ष";"अध्वन्"->"अध्व";"अङ्गुलि"->"अङ्गुल";"रात्रि"->"रात्र";"उरस्"->"उरस";"वर्चस्"->"वर्चस";"तमस्"->"तमस";"रहस्"->"रहस";"वसीयस्"->"वसीयस";"श्रेयस्"->"श्रेयस";"अनस्"->"अनस";"अश्मन्"->"अश्म";"अयस्"->"अयस";"सरस्"->"सरस";"तक्षन्"->"तक्ष";"श्वन्"->"श्व";"सक्थि"->"सक्थ";"खारी"->"खार";"अञ्जलि"->"अञ्जल";else->if(u.endsWith("न्"))u.dropLast(2) else u}; return leading(c)+x }

object AcaturadicCanonicalSutra : ActiveSamasantaSutra(77,"अचतुरविचतुरसुचतुरस्त्रीपुंसधेन्वनडुहर्क्सामवाङ्मनसाक्षिभ्रुवदारगवोर्वष्ठीवपदष्ठीवनक्तंदिवरत्रिंदिवाहर्दिवसरजसनिःश्रेयसपुरुषायुषद्व्यायुषत्र्यायुषर्ग्यजुषजातोक्षमहोक्षवृद्धोक्षोपशुनगोष्ठश्वाः",samasaType=SamasaType.TATPURUSA,priority=60){
    private val forms=mapOf("अ"+"चतुर्" to "अचतुर","वि"+"चतुर्" to "विचतुर","सु"+"चतुर्" to "सुचतुर","नक्तम्"+"दिव" to "नक्तंदिव","रात्रिम्"+"दिव" to "रात्रिंदिव","अहर्"+"दिव" to "अहर्दिव")
    override fun matches(context:SamasaRuleContext)=context.padas.size>=2&&forms.containsKey(context.purvaPada.upadesha+context.uttaraPada.upadesha)
    override fun apply(context:SamasaRuleContext)=formed(context,forms.getValue(context.purvaPada.upadesha+context.uttaraPada.upadesha))
}
object BrahmahastibhyamVarcasahSutra:ActiveSamasantaSutra(78,"ब्रह्महस्तिभ्यां वर्चसः",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("ब्रह्म","हस्तिन्")&&c.uttaraPada.upadesha=="वर्चस्";override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object AvasamandhebhyasTamasahSutra:ActiveSamasantaSutra(79,"अवसमन्धेभ्यस्तमसः",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("अव","सम्","अन्ध")&&c.uttaraPada.upadesha=="तमस्";override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object SvasoVasiyahSreyasahSutra:ActiveSamasantaSutra(80,"श्वसो वसीयःश्रेयसः",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha=="श्वस्"&&c.uttaraPada.upadesha in setOf("वसीयस्","श्रेयस्");override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object AnvavataptadRahasahSutra:ActiveSamasantaSutra(81,"अन्ववतप्ताद्रहसः",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("अनु","अव","तप्त")&&c.uttaraPada.upadesha=="रहस्";override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object PraterUrasahSaptamisthatSutra:ActiveSamasantaSutra(82,"प्रतेरुरसः सप्तमीस्थात्",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha=="प्रति"&&c.uttaraPada.upadesha=="उरस्"&&c.uttaraPada.vibhakti==Vibhakti.SAPTAMI;override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object AnugavamAyameSutra:ActiveSamasantaSutra(83,"अनुगवमायामे",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha=="अनु"&&c.uttaraPada.upadesha=="गो"&&SamasaSemanticRelation.MEASURE_DIMENSION in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(c,"अनुगव")}
object DvistavaTristavaVedihSutra:ActiveSamasantaSutra(84,"द्विस्तावा त्रिस्तावा वेदिः",samasaType=SamasaType.DVIGU){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("द्वि","त्रि")&&c.uttaraPada.upadesha=="स्ताव";override fun apply(c:SamasaRuleContext)=formed(c,(if(c.purvaPada.upadesha=="द्वि")"द्विस्ताव" else "त्रिस्ताव"))}
object AhasRatrehSutra:ActiveSamasantaSutra(87,"अहस्सर्वैकदेशसंख्यातपुण्याच्च रात्रेः",samasaType=SamasaType.TATPURUSA){private val first=setOf("अहन्","सर्व","पूर्व","अपर","संख्यात","पुण्य");override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in first&&c.uttaraPada.upadesha=="रात्रि";override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}

object GorAtaddhitalukiSutra:ActiveSamasantaSutra(92,"गोरतद्धितलुकि",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="गो"&&SamasaMorphologicalFeature.TADDHITA_LUK !in c.uttaraPada.morphologicalFeatures;override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object AgrakhyayamUrasahSutra:ActiveSamasantaSutra(93,"अग्राख्यायामुरसः",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="उरस्"&&SamasaSemanticRelation.PRAISE in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object AnoAsmayassarasamJatisamjnayohSutra:ActiveSamasantaSutra(94,"अनोऽश्मायस्सरसां जातिसंज्ञयोः",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha in setOf("अनस्","अश्मन्","अयस्","सरस्")&&c.semanticRelations.any{it==SamasaSemanticRelation.SPECIES||it==SamasaSemanticRelation.PROPER_NAME};override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object GramakautabhyamCaTaksnahSutra:ActiveSamasantaSutra(95,"ग्रामकौटाभ्यां च तक्ष्णः",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("ग्राम","कौट")&&c.uttaraPada.upadesha=="तक्षन्";override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object AtehSunahSutra:ActiveSamasantaSutra(96,"अतेः शुनः",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha=="अति"&&c.uttaraPada.upadesha=="श्वन्";override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object UpamanadApranisuSutra:ActiveSamasantaSutra(97,"उपमानादप्राणिषु",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="श्वन्"&&SamasaSemanticRelation.NON_ANIMATE_REFERENT in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object UttaramrgapurvacCaSakthnahSutra:ActiveSamasantaSutra(98,"उत्तरमृगपूर्वाच्च सक्थ्नः",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("उत्तर","मृग","पर्व")&&c.uttaraPada.upadesha=="सक्थि";override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object NavoDvigohSutra:ActiveSamasantaSutra(99,"नावो द्विगोः",samasaType=SamasaType.DVIGU){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha in setOf("नौ","नाव");override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}

object AnasantanNapumsakacChandasiSutra:ActiveSamasantaSutra(103,"अनसन्तान्नपुंसकाच्छन्दसि",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.outputLinga==Linga.NAPUMSAKA&&SamasaSemanticRelation.VEDIC_REGISTER in c.semanticRelations&&(c.uttaraPada.upadesha.endsWith("न्")||c.uttaraPada.upadesha.endsWith("स्"));override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object BrahmanoJanapadakhyayamSutra:ActiveSamasantaSutra(104,"ब्रह्मणो जानपदाख्यायाम्",samasaType=SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="ब्राह्मण"&&SamasaSemanticRelation.COUNTRY_PERSON in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(c,members(c))}
object KumahadbhyamAnyatarasyamSutra:ActiveSamasantaSutra(105,"कुमहद्भ्यामन्यतरस्याम्",true,SamasaType.TATPURUSA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("कु","महत्")&&c.uttaraPada.upadesha=="ब्रह्मन्";override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object DvandvacCudasahantatSamahareSutra:ActiveSamasantaSutra(106,"द्वन्द्वाच्चुदषहान्तात् समाहारे",samasaType=SamasaType.DVANDVA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&SamasaSemanticRelation.COLLECTIVE in c.semanticRelations&&c.uttaraPada.upadesha.lastOrNull() in setOf('च','छ','ज','झ','ञ','द','ष','ह','्');override fun apply(c:SamasaRuleContext)=formed(c,members(c))}
object AvyayibhaveSaratprabhrtibhyahSutra:ActiveSamasantaSutra(107,"अव्ययीभावे शरत्प्रभृतिभ्यः",samasaType=SamasaType.AVYAYIBHAVA){private val words=setOf("शरद्","वर्ष","अहन्","रात्रि");override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha in words;override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object AnasCaSutra:ActiveSamasantaSutra(108,"अनश्च",samasaType=SamasaType.AVYAYIBHAVA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha.endsWith("अन्");override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object NapumsakadAnyatarasyamSutra:ActiveSamasantaSutra(109,"नपुंसकादन्यतरस्याम्",true,SamasaType.AVYAYIBHAVA,20){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.linga==Linga.NAPUMSAKA&&c.uttaraPada.upadesha.endsWith("अन्");override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object NadipaurnamasyagrahayanibhyahSutra:ActiveSamasantaSutra(110,"नदीपौर्णमास्याग्रहायणीभ्यः",true,SamasaType.AVYAYIBHAVA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha in setOf("नदी","पौर्णमासी","आग्रहायणी");override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
object JhayahSutra:ActiveSamasantaSutra(111,"झयः",true,SamasaType.AVYAYIBHAVA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha.lastOrNull() in setOf('क','ख','ग','घ','च','छ','ज','झ','ट','ठ','ड','ढ','त','थ','द','ध','प','फ','ब','भ');override fun apply(c:SamasaRuleContext)=formed(c,members(c))}
object GiresCaSenakasyaSutra:ActiveSamasantaSutra(112,"गिरेश्च सेनकस्य",samasaType=SamasaType.AVYAYIBHAVA){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="गिरि";override fun apply(c:SamasaRuleContext)=formed(c,finalAsA(c))}
