package dev.panini.ashtadhyayi.adhyaya5.pada4

import dev.panini.analysis.*
import dev.panini.core.*
import dev.panini.shiksha.Samjna
import dev.panini.sutra.*

private fun all(c:SamasaRuleContext)=c.padas.joinToString(""){it.upadesha}
private fun lead(c:SamasaRuleContext)=c.padas.dropLast(1).joinToString(""){it.upadesha}
private fun withLast(c:SamasaRuleContext,last:String)=lead(c)+last
private fun shortRFinal(w:String)=w.endsWith("ृ")||w.endsWith("ऋ")

object AngulerDaruniSutra:ActiveSamasantaSutra(114,"अङ्गुलेर्दारुणि",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="अङ्गुलि"&&SamasaSemanticRelation.WOODEN_OBJECT in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(withLast(c,"अङ्गुल"))}
object DvitribhyamSaMurdhnahSutra:ActiveSamasantaSutra(115,"द्वित्रिभ्यां ष मूर्ध्नः",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("द्वि","त्रि")&&c.uttaraPada.upadesha in setOf("मूर्धन्","मूर्धन");override fun apply(c:SamasaRuleContext)=formed(withLast(c,"मूर्ध"))}
object ApPuraniPramanyohSutra:ActiveSamasantaSutra(116,"अप् पूरणीप्रमाण्योः",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&(SamasaMorphologicalFeature.ORDINAL in c.uttaraPada.morphologicalFeatures||c.uttaraPada.upadesha=="प्रमाणी");override fun apply(c:SamasaRuleContext)=formed(all(c)+"अ")}
object AntarbahirbhyamCaLomnahSutra:ActiveSamasantaSutra(117,"अन्तर्बहिर्भ्यां च लोम्नः",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("अन्तर्","बहिस्","बहिर्")&&c.uttaraPada.upadesha=="लोमन्";override fun apply(c:SamasaRuleContext)=formed(withLast(c,"लोम"))}
object AnNasikayahSamjnayamNasamCasthulatSutra:ActiveSamasantaSutra(118,"अञ्नासिकायाः संज्ञायां नसं चास्थूलात्",samasaType=SamasaType.BAHUVRIHI,priority=30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="नासिका"&&c.purvaPada.upadesha!="स्थूल"&&SamasaSemanticRelation.PROPER_NAME in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(withLast(c,"नस"))}
object UpasargacCaSutra:ActiveSamasantaSutra(119,"उपसर्गाच्च",samasaType=SamasaType.BAHUVRIHI,priority=40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="नासिका"&&Samjna.UPASARGA in c.purvaPada.samjnas;override fun apply(c:SamasaRuleContext)=formed(withLast(c,"नस"))}
object SupratasusvasudivaCanonicalSutra:ActiveSamasantaSutra(120,"सुप्रातसुश्वसुदिवशारिकुक्षचतुरश्रैणीपदाजपदप्रोष्ठपदाः",samasaType=SamasaType.BAHUVRIHI,priority=60){private val forms=mapOf("सु|प्रात" to "सुप्रात","सु|श्वस्" to "सुश्व","सु|दिव" to "सुदिव","शारि|कुक्षि" to "शारिकुक्ष","चतुर्|अश्र" to "चतुरश्र","एणी|पाद" to "एणीपद","अज|पाद" to "अजपद","प्रोष्ठ|पाद" to "प्रोष्ठपद");override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&forms.containsKey(c.purvaPada.upadesha+"|"+c.uttaraPada.upadesha);override fun apply(c:SamasaRuleContext)=formed(forms.getValue(c.purvaPada.upadesha+"|"+c.uttaraPada.upadesha))}
object NanjDuhSubhyoHalisakthyorAnyatarasyamSutra:ActiveSamasantaSutra(121,"नञ्दुःसुभ्यो हलिसक्थ्योरन्यतरस्याम्",true,SamasaType.BAHUVRIHI,30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("न","नञ्","दुस्","दुर्","सु")&&c.uttaraPada.upadesha in setOf("हलि","सक्थि");override fun apply(c:SamasaRuleContext)=formed(withLast(c,if(c.uttaraPada.upadesha=="हलि")"हल" else "सक्थ"))}
object NityamAsicPrajaMedhayohSutra:ActiveSamasantaSutra(122,"नित्यमसिच् प्रजामेधयोः",samasaType=SamasaType.BAHUVRIHI,priority=40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("न","नञ्","दुस्","दुर्","सु")&&c.uttaraPada.upadesha in setOf("प्रजा","मेधा");override fun apply(c:SamasaRuleContext)=formed(withLast(c,c.uttaraPada.upadesha.dropLast(1)+"स्"))}
object BahuprajasChandasiSutra:ActiveSamasantaSutra(123,"बहुप्रजाश्छन्दसि",samasaType=SamasaType.BAHUVRIHI,priority=50){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha=="बहु"&&c.uttaraPada.upadesha=="प्रजा"&&SamasaSemanticRelation.VEDIC_REGISTER in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed("बहुप्रजस्")}
object DharmadAnicKevalatSutra:ActiveSamasantaSutra(124,"धर्मादनिच् केवलात्",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size==2&&c.uttaraPada.upadesha=="धर्म";override fun apply(c:SamasaRuleContext)=formed(withLast(c,"धर्मन्"))}
object JambhaSuharitaTrnaSomebhyahSutra:ActiveSamasantaSutra(125,"जम्भा सुहरिततृणसोमेभ्यः",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("सु","हरित","तृण","सोम")&&c.uttaraPada.upadesha in setOf("जम्भ","जम्भा");override fun apply(c:SamasaRuleContext)=formed(withLast(c,"जम्भन्"))}
object DaksinerMaLubdhayogeSutra:ActiveSamasantaSutra(126,"दक्षिणेर्मा लुब्धयोगे",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("दक्षिण","दक्षिणा")&&SamasaSemanticRelation.HUNTER_ASSOCIATION in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed("दक्षिणेर्मन्")}
object IcKarmavyatihareSutra:ActiveSamasantaSutra(127,"इच् कर्मव्यतिहारे",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&SamasaSemanticRelation.RECIPROCAL_ACTION in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(all(c)+"ि")}
object DvidandyadibhyasCaSutra:ActiveSamasantaSutra(128,"द्विदण्ड्यादिभ्यश्च",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&SamasaSemanticRelation.LEXICAL_GANA_MEMBERSHIP in c.semanticRelations&&c.purvaPada.upadesha in setOf("द्वि","त्रि");override fun apply(c:SamasaRuleContext)=formed(all(c)+"ि")}
object PrasambhyamJanunorJnuhSutra:ActiveSamasantaSutra(129,"प्रसम्भ्यां जानुनोर्ज्ञुः",samasaType=SamasaType.BAHUVRIHI,priority=40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("प्र","सम्")&&c.uttaraPada.upadesha in setOf("जानु","जानुन्");override fun apply(c:SamasaRuleContext)=formed(withLast(c,"ज्ञु"))}
object UrdhvadVibhasaSutra:ActiveSamasantaSutra(130,"ऊर्ध्वाद्विभाषा",true,SamasaType.BAHUVRIHI,40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha=="ऊर्ध्व"&&c.uttaraPada.upadesha in setOf("जानु","जानुन्");override fun apply(c:SamasaRuleContext)=formed(withLast(c,"ज्ञु"))}
object UdhasoAnanSutra:ActiveSamasantaSutra(131,"ऊधसोऽनङ्",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="ऊधस्";override fun apply(c:SamasaRuleContext)=formed(withLast(c,"ऊधन्"))}
object DhanusasCaSutra:ActiveSamasantaSutra(132,"धनुषश्च",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="धनुस्";override fun apply(c:SamasaRuleContext)=formed(withLast(c,"धन्वन्"))}
object VaSamjnayamSutra:ActiveSamasantaSutra(133,"वा संज्ञायाम्",true,SamasaType.BAHUVRIHI,30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha in setOf("ऊधस्","धनुस्")&&SamasaSemanticRelation.PROPER_NAME in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(all(c))}
object JayayaNinSutra:ActiveSamasantaSutra(134,"जायाया निङ्",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="जाया";override fun apply(c:SamasaRuleContext)=formed(withLast(c,"जानि"))}
object GandhasyedutputisusurabhibhyahSutra:ActiveSamasantaSutra(135,"गन्धस्येदुत्पूतिसुसुरभिभ्यः",samasaType=SamasaType.BAHUVRIHI,priority=40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("उत्","पूति","सु","सुरभि")&&c.uttaraPada.upadesha=="गन्ध";override fun apply(c:SamasaRuleContext)=formed(withLast(c,"गन्धि"))}
object AlpakhyayamSutra:ActiveSamasantaSutra(136,"अल्पाख्यायाम्",samasaType=SamasaType.BAHUVRIHI,priority=30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="गन्ध"&&SamasaSemanticRelation.SMALL_QUANTITY in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(withLast(c,"गन्धि"))}
object UpamanacCaSutra:ActiveSamasantaSutra(137,"उपमानाच्च",samasaType=SamasaType.BAHUVRIHI,priority=30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="गन्ध"&&SamasaSemanticRelation.QUALIFIER_QUALIFIED in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(withLast(c,"गन्धि"))}
object PadasyaLopoAhastyadibhyahSutra:ActiveSamasantaSutra(138,"पादस्य लोपोऽहस्त्यादिभ्यः",samasaType=SamasaType.BAHUVRIHI,priority=20){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="पाद"&&c.purvaPada.upadesha!="हस्तिन्"&&SamasaSemanticRelation.QUALIFIER_QUALIFIED in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(withLast(c,"पद्"))}
object KumbhapadisuCaSutra:ActiveSamasantaSutra(139,"कुम्भपदीषु च",samasaType=SamasaType.BAHUVRIHI,priority=50){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&(c.purvaPada.upadesha+"|"+c.uttaraPada.upadesha) in setOf("कुम्भ|पाद","शङ्ख|पाद");override fun apply(c:SamasaRuleContext)=formed(withLast(c,"पद्"))}
object SankhyasupurvasyaSutra:ActiveSamasantaSutra(140,"संख्यासुपूर्वस्य",samasaType=SamasaType.BAHUVRIHI,priority=40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="पाद"&&(Samjna.SANKHYA in c.purvaPada.samjnas||c.purvaPada.upadesha=="सु");override fun apply(c:SamasaRuleContext)=formed(withLast(c,"पद्"))}
object VayasiDantasyaDatruSutra:ActiveSamasantaSutra(141,"वयसि दन्तस्य दतृ",samasaType=SamasaType.BAHUVRIHI,priority=50){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="दन्त"&&SamasaSemanticRelation.AGE_STAGE in c.semanticRelations&&(Samjna.SANKHYA in c.purvaPada.samjnas||c.purvaPada.upadesha=="सु");override fun apply(c:SamasaRuleContext)=formed(withLast(c,"दतृ"))}
object ChandasiCaSutra:ActiveSamasantaSutra(142,"छन्दसि च",samasaType=SamasaType.BAHUVRIHI,priority=20){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="दन्त"&&SamasaSemanticRelation.VEDIC_REGISTER in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(withLast(c,"दत्"))}
object StriyamSamjnayamSutra:ActiveSamasantaSutra(143,"स्त्रियां संज्ञायाम्",samasaType=SamasaType.BAHUVRIHI,priority=30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="दन्त"&&c.outputLinga==Linga.STRI&&SamasaSemanticRelation.PROPER_NAME in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(withLast(c,"दत्"))}
object VibhasaSyavarokabhyamSutra:ActiveSamasantaSutra(144,"विभाषा श्यावारोकाभ्याम्",true,SamasaType.BAHUVRIHI,40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("श्याव","अरोक")&&c.uttaraPada.upadesha=="दन्त";override fun apply(c:SamasaRuleContext)=formed(withLast(c,"दत्"))}
object AgrantasuddhasubhravrsavarahebhyasCaSutra:ActiveSamasantaSutra(145,"अग्रान्तशुद्धशुभ्रवृषवराहेभ्यश्च",true,SamasaType.BAHUVRIHI,40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&(c.purvaPada.upadesha.endsWith("अग्र")||c.purvaPada.upadesha in setOf("शुद्ध","शुभ्र","वृष","वराह"))&&c.uttaraPada.upadesha=="दन्त";override fun apply(c:SamasaRuleContext)=formed(withLast(c,"दत्"))}
object KakudasyavasthayamLopahSutra:ActiveSamasantaSutra(146,"ककुदस्यावस्थायां लोपः",samasaType=SamasaType.BAHUVRIHI,priority=30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="ककुद"&&SamasaSemanticRelation.ANIMAL_CONDITION in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(withLast(c,"ककुद्"))}
object TrikakutParvateSutra:ActiveSamasantaSutra(147,"त्रिककुत् पर्वते",samasaType=SamasaType.BAHUVRIHI,priority=60){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha=="त्रि"&&c.uttaraPada.upadesha=="ककुद"&&SamasaSemanticRelation.PROPER_NAME in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed("त्रिककुत्")}
object UdvibhyamKakudasyaSutra:ActiveSamasantaSutra(148,"उद्विभ्यां काकुदस्य",samasaType=SamasaType.BAHUVRIHI,priority=50){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("उत्","वि")&&c.uttaraPada.upadesha=="ककुद";override fun apply(c:SamasaRuleContext)=formed(withLast(c,"ककुद्"))}
object PurnadVibhasaSutra:ActiveSamasantaSutra(149,"पूर्णाद्विभाषा",true,SamasaType.BAHUVRIHI,50){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha=="पूर्ण"&&c.uttaraPada.upadesha=="ककुद";override fun apply(c:SamasaRuleContext)=formed(withLast(c,"ककुद्"))}

object InahStriyamSutra:ActiveSamasantaSutra(152,"इनः स्त्रियाम्",samasaType=SamasaType.BAHUVRIHI,priority=30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.outputLinga==Linga.STRI&&c.uttaraPada.upadesha.endsWith("इन्");override fun apply(c:SamasaRuleContext)=formed(all(c)+"क")}
object SesadVibhasaCanonicalSutra:ActiveSamasantaSutra(154,"शेषाद्विभाषा",true,SamasaType.BAHUVRIHI,5){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&SamasaSemanticRelation.RESIDUAL_KAP_OPTION in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formed(all(c)+"क")}
object NaSamjnayamSutra:Sutra<SamasaRuleContext,SamasaRuleResult>(number="5.4.155",text="न संज्ञायाम्",hindiExplanation="संज्ञा में कप् का निषेध होता है।",type=SutraType.NISHEDHA,chapter=5,pada=4,optional=false,kramaValue=540155,role=SutraRole.Niyama,action=SutraAction.NISHEDHA,scope=SutraScope.DERIVATION,samasaType=SamasaType.BAHUVRIHI,samasaPriority=80),SamasaSutra{override fun matches(c:SamasaRuleContext)=c.samasaType==SamasaType.BAHUVRIHI&&SamasaSemanticRelation.PROPER_NAME in c.semanticRelations;override fun apply(c:SamasaRuleContext)=SamasaRuleResult.NotApplicable}
object IyasasCaSutra:Sutra<SamasaRuleContext,SamasaRuleResult>(number="5.4.156",text="ईयसश्च",hindiExplanation="ईयस्-अन्त बहुव्रीहि में कप् का निषेध होता है।",type=SutraType.NISHEDHA,chapter=5,pada=4,optional=false,kramaValue=540156,role=SutraRole.Niyama,action=SutraAction.NISHEDHA,scope=SutraScope.DERIVATION,samasaType=SamasaType.BAHUVRIHI,samasaPriority=80),SamasaSutra{override fun matches(c:SamasaRuleContext)=SamasaMorphologicalFeature.IYAS_ENDING in c.uttaraPada.morphologicalFeatures;override fun apply(c:SamasaRuleContext)=SamasaRuleResult.NotApplicable}
object VanditeBhratuhSutra:Sutra<SamasaRuleContext,SamasaRuleResult>(number="5.4.157",text="वन्दिते भ्रातुः",hindiExplanation="वन्दित भ्रातृ-अर्थ में कप् का निषेध होता है।",type=SutraType.NISHEDHA,chapter=5,pada=4,optional=false,kramaValue=540157,role=SutraRole.Niyama,action=SutraAction.NISHEDHA,scope=SutraScope.DERIVATION,samasaType=SamasaType.BAHUVRIHI,samasaPriority=80),SamasaSutra{override fun matches(c:SamasaRuleContext)=c.uttaraPada.upadesha=="भ्रातृ"&&SamasaSemanticRelation.PRAISED_REFERENT in c.semanticRelations;override fun apply(c:SamasaRuleContext)=SamasaRuleResult.NotApplicable}
object RtasChandasiSutra:Sutra<SamasaRuleContext,SamasaRuleResult>(number="5.4.158",text="ऋतश्छन्दसि",hindiExplanation="छन्दस् में ऋकारान्त बहुव्रीहि में कप् का निषेध होता है।",type=SutraType.NISHEDHA,chapter=5,pada=4,optional=false,kramaValue=540158,role=SutraRole.Niyama,action=SutraAction.NISHEDHA,scope=SutraScope.DERIVATION,samasaType=SamasaType.BAHUVRIHI,samasaPriority=80),SamasaSutra{override fun matches(c:SamasaRuleContext)=shortRFinal(c.uttaraPada.upadesha)&&SamasaSemanticRelation.VEDIC_REGISTER in c.semanticRelations;override fun apply(c:SamasaRuleContext)=SamasaRuleResult.NotApplicable}
object NaditantryohSvangeSutra:Sutra<SamasaRuleContext,SamasaRuleResult>(number="5.4.159",text="नाडीतन्त्र्योः स्वाङ्गे",hindiExplanation="स्वाङ्गवाची नाडी और तन्त्री में कप् का निषेध होता है।",type=SutraType.NISHEDHA,chapter=5,pada=4,optional=false,kramaValue=540159,role=SutraRole.Niyama,action=SutraAction.NISHEDHA,scope=SutraScope.DERIVATION,samasaType=SamasaType.BAHUVRIHI,samasaPriority=80),SamasaSutra{override fun matches(c:SamasaRuleContext)=c.uttaraPada.upadesha in setOf("नाडी","तन्त्री")&&SamasaSemanticRelation.BODY_PART in c.semanticRelations;override fun apply(c:SamasaRuleContext)=SamasaRuleResult.NotApplicable}
object NispravanisCaSutra:ActiveSamasantaSutra(160,"निष्प्रवाणिश्च",samasaType=SamasaType.BAHUVRIHI,priority=90){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("निस्","निष्")&&c.uttaraPada.upadesha=="प्रवाणी";override fun apply(c:SamasaRuleContext)=formed("निष्प्रवाणि")}
