package dev.panini.ashtadhyayi.adhyaya5.pada4

import dev.panini.analysis.*
import dev.panini.core.*
import dev.panini.shiksha.*
import dev.panini.sutra.*

private fun shortRFinal(pada:SamasaPada)=pada.varnas.lastOrNull()==Svara.R

object AngulerDaruniSutra:ActiveSamasantaSutra(114,"अङ्गुलेर्दारुणि",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="अङ्गुलि"&&SamasaSemanticRelation.WOODEN_OBJECT in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1)+Svara.A)}
object DvitribhyamSaMurdhnahSutra:ActiveSamasantaSutra(115,"द्वित्रिभ्यां ष मूर्ध्नः",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("द्वि","त्रि")&&c.uttaraPada.upadesha in setOf("मूर्धन्","मूर्धन");override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.MA,Svara.UU,Vyanjana.RA,Vyanjana.DHA,Svara.A))}
object ApPuraniPramanyohSutra:ActiveSamasantaSutra(116,"अप् पूरणीप्रमाण्योः",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&(SamasaMorphologicalFeature.ORDINAL in c.uttaraPada.morphologicalFeatures||c.uttaraPada.upadesha=="प्रमाणी");override fun apply(c:SamasaRuleContext)=formedWithSuffix(c,listOf(Svara.A))}
object AntarbahirbhyamCaLomnahSutra:ActiveSamasantaSutra(117,"अन्तर्बहिर्भ्यां च लोम्नः",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("अन्तर्","बहिस्","बहिर्")&&c.uttaraPada.upadesha=="लोमन्";override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1))}
object AnNasikayahSamjnayamNasamCasthulatSutra:ActiveSamasantaSutra(118,"अञ्नासिकायाः संज्ञायां नसं चास्थूलात्",samasaType=SamasaType.BAHUVRIHI,priority=30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="नासिका"&&c.purvaPada.upadesha!="स्थूल"&&SamasaSemanticRelation.PROPER_NAME in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.NA,Svara.A,Vyanjana.SA,Svara.A))}
object UpasargacCaSutra:ActiveSamasantaSutra(119,"उपसर्गाच्च",samasaType=SamasaType.BAHUVRIHI,priority=40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="नासिका"&&Samjna.UPASARGA in c.purvaPada.samjnas;override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.NA,Svara.A,Vyanjana.SA,Svara.A))}
object SupratasusvasudivaCanonicalSutra : ActiveSamasantaSutra(
    120, "सुप्रातसुश्वसुदिवशारिकुक्षचतुरश्रैणीपदाजपदप्रोष्ठपदाः",
    samasaType = SamasaType.BAHUVRIHI, priority = 60,
) {
    private enum class Prescription { UNCHANGED, FINAL_S_LOPA, FINAL_I_TO_A, PADA_SHORTENING }
    private val prescriptions = mapOf(
        ("सु" to "प्रात") to Prescription.UNCHANGED,
        ("सु" to "श्वस्") to Prescription.FINAL_S_LOPA,
        ("सु" to "दिव") to Prescription.UNCHANGED,
        ("शारि" to "कुक्षि") to Prescription.FINAL_I_TO_A,
        ("चतुर्" to "अश्र") to Prescription.UNCHANGED,
        ("एणी" to "पाद") to Prescription.PADA_SHORTENING,
        ("अज" to "पाद") to Prescription.PADA_SHORTENING,
        ("प्रोष्ठ" to "पाद") to Prescription.PADA_SHORTENING,
    )
    override fun matches(c: SamasaRuleContext) = c.padas.size >= 2 &&
        (c.purvaPada.upadesha to c.uttaraPada.upadesha) in prescriptions

    override fun apply(c: SamasaRuleContext): SamasaRuleResult.Formed {
        val member = c.uttaraPada.varnas
        val replacement = when (prescriptions.getValue(c.purvaPada.upadesha to c.uttaraPada.upadesha)) {
            Prescription.UNCHANGED -> member
            Prescription.FINAL_S_LOPA -> member.dropLast(1)
            Prescription.FINAL_I_TO_A -> member.dropLast(1) + Svara.A
            Prescription.PADA_SHORTENING -> member.mapIndexed { index, varna ->
                if (index == 1) Svara.A else varna
            }
        }
        return formedWithFinalMember(c, replacement)
    }
}
object NanjDuhSubhyoHalisakthyorAnyatarasyamSutra:ActiveSamasantaSutra(121,"नञ्दुःसुभ्यो हलिसक्थ्योरन्यतरस्याम्",true,SamasaType.BAHUVRIHI,30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("न","नञ्","दुस्","दुर्","सु")&&c.uttaraPada.upadesha in setOf("हलि","सक्थि");override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1)+Svara.A)}
object NityamAsicPrajaMedhayohSutra:ActiveSamasantaSutra(122,"नित्यमसिच् प्रजामेधयोः",samasaType=SamasaType.BAHUVRIHI,priority=40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("न","नञ्","दुस्","दुर्","सु")&&c.uttaraPada.upadesha in setOf("प्रजा","मेधा");override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1)+listOf(Svara.A,Vyanjana.SA))}
object BahuprajasChandasiSutra:ActiveSamasantaSutra(123,"बहुप्रजाश्छन्दसि",samasaType=SamasaType.BAHUVRIHI,priority=50){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha=="बहु"&&c.uttaraPada.upadesha=="प्रजा"&&SamasaSemanticRelation.VEDIC_REGISTER in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1)+listOf(Svara.A,Vyanjana.SA))}
object DharmadAnicKevalatSutra:ActiveSamasantaSutra(124,"धर्मादनिच् केवलात्",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size==2&&c.uttaraPada.upadesha=="धर्म";override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas+Vyanjana.NA)}
object JambhaSuharitaTrnaSomebhyahSutra:ActiveSamasantaSutra(125,"जम्भा सुहरिततृणसोमेभ्यः",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("सु","हरित","तृण","सोम")&&c.uttaraPada.upadesha in setOf("जम्भ","जम्भा");override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1)+listOf(Svara.A,Vyanjana.NA))}
object DaksinerMaLubdhayogeSutra:ActiveSamasantaSutra(126,"दक्षिणेर्मा लुब्धयोगे",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size==2&&c.purvaPada.upadesha in setOf("दक्षिण","दक्षिणा")&&c.uttaraPada.upadesha=="ईर्म"&&SamasaSemanticRelation.HUNTER_ASSOCIATION in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas+Vyanjana.NA)}
object IcKarmavyatihareSutra:ActiveSamasantaSutra(127,"इच् कर्मव्यतिहारे",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&SamasaSemanticRelation.RECIPROCAL_ACTION in c.semanticRelations;override fun apply(c:SamasaRuleContext)=SamasaRuleResult.Formed((c.padas.dropLast(1).flatMap { it.varnas }+c.uttaraPada.varnas.dropLast(1)+Svara.I).toDevanagari(),"$number substitutes इ at the final member boundary.",memberEdits=mapOf(c.padas.lastIndex to (c.uttaraPada.varnas.dropLast(1)+Svara.I).toDevanagari()))}
object DvidandyadibhyasCaSutra:ActiveSamasantaSutra(128,"द्विदण्ड्यादिभ्यश्च",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&SamasaSemanticRelation.LEXICAL_GANA_MEMBERSHIP in c.semanticRelations&&c.purvaPada.upadesha in setOf("द्वि","त्रि");override fun apply(c:SamasaRuleContext)=SamasaRuleResult.Formed((c.padas.dropLast(1).flatMap { it.varnas }+c.uttaraPada.varnas.dropLast(1)+Svara.I).toDevanagari(),"$number substitutes इ at the final member boundary.",memberEdits=mapOf(c.padas.lastIndex to (c.uttaraPada.varnas.dropLast(1)+Svara.I).toDevanagari()))}
object PrasambhyamJanunorJnuhSutra:ActiveSamasantaSutra(129,"प्रसम्भ्यां जानुनोर्ज्ञुः",samasaType=SamasaType.BAHUVRIHI,priority=40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("प्र","सम्")&&c.uttaraPada.upadesha in setOf("जानु","जानुन्");override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.JA,Vyanjana.NYA,Svara.U))}
object UrdhvadVibhasaSutra:ActiveSamasantaSutra(130,"ऊर्ध्वाद्विभाषा",true,SamasaType.BAHUVRIHI,40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha=="ऊर्ध्व"&&c.uttaraPada.upadesha in setOf("जानु","जानुन्");override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.JA,Vyanjana.NYA,Svara.U))}
object UdhasoAnanSutra:ActiveSamasantaSutra(131,"ऊधसोऽनङ्",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="ऊधस्";override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1)+Vyanjana.NA)}
object DhanusasCaSutra:ActiveSamasantaSutra(132,"धनुषश्च",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="धनुस्";override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(2)+listOf(Vyanjana.VA,Svara.A,Vyanjana.NA))}
object VaSamjnayamSutra:ActiveSamasantaSutra(133,"वा संज्ञायाम्",true,SamasaType.BAHUVRIHI,30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha in setOf("ऊधस्","धनुस्")&&SamasaSemanticRelation.PROPER_NAME in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithSuffix(c,emptyList())}
object JayayaNinSutra:ActiveSamasantaSutra(134,"जायाया निङ्",samasaType=SamasaType.BAHUVRIHI){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="जाया";override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(2)+listOf(Vyanjana.NA,Svara.I))}
object GandhasyedutputisusurabhibhyahSutra:ActiveSamasantaSutra(135,"गन्धस्येदुत्पूतिसुसुरभिभ्यः",samasaType=SamasaType.BAHUVRIHI,priority=40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("उत्","पूति","सु","सुरभि")&&c.uttaraPada.upadesha=="गन्ध";override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1)+Svara.I)}
object AlpakhyayamSutra:ActiveSamasantaSutra(136,"अल्पाख्यायाम्",samasaType=SamasaType.BAHUVRIHI,priority=30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="गन्ध"&&SamasaSemanticRelation.SMALL_QUANTITY in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1)+Svara.I)}
object UpamanacCaSutra:ActiveSamasantaSutra(137,"उपमानाच्च",samasaType=SamasaType.BAHUVRIHI,priority=30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="गन्ध"&&SamasaSemanticRelation.QUALIFIER_QUALIFIED in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1)+Svara.I)}
object PadasyaLopoAhastyadibhyahSutra:ActiveSamasantaSutra(138,"पादस्य लोपोऽहस्त्यादिभ्यः",samasaType=SamasaType.BAHUVRIHI,priority=20){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="पाद"&&c.purvaPada.upadesha!="हस्तिन्"&&SamasaSemanticRelation.QUALIFIER_QUALIFIED in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.PA,Svara.A,Vyanjana.DA))}
object KumbhapadisuCaSutra:ActiveSamasantaSutra(139,"कुम्भपदीषु च",samasaType=SamasaType.BAHUVRIHI,priority=50){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&(c.purvaPada.upadesha+"|"+c.uttaraPada.upadesha) in setOf("कुम्भ|पाद","शङ्ख|पाद");override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.PA,Svara.A,Vyanjana.DA))}
object SankhyasupurvasyaSutra:ActiveSamasantaSutra(140,"संख्यासुपूर्वस्य",samasaType=SamasaType.BAHUVRIHI,priority=40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="पाद"&&(Samjna.SANKHYA in c.purvaPada.samjnas||c.purvaPada.upadesha=="सु");override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.PA,Svara.A,Vyanjana.DA))}
object VayasiDantasyaDatruSutra:ActiveSamasantaSutra(141,"वयसि दन्तस्य दतृ",samasaType=SamasaType.BAHUVRIHI,priority=50){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="दन्त"&&SamasaSemanticRelation.AGE_STAGE in c.semanticRelations&&(Samjna.SANKHYA in c.purvaPada.samjnas||c.purvaPada.upadesha=="सु");override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.DA,Svara.A,Vyanjana.TA,Svara.R))}
object ChandasiCaSutra:ActiveSamasantaSutra(142,"छन्दसि च",samasaType=SamasaType.BAHUVRIHI,priority=20){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="दन्त"&&SamasaSemanticRelation.VEDIC_REGISTER in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.DA,Svara.A,Vyanjana.TA))}
object StriyamSamjnayamSutra:ActiveSamasantaSutra(143,"स्त्रियां संज्ञायाम्",samasaType=SamasaType.BAHUVRIHI,priority=30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="दन्त"&&c.outputLinga==Linga.STRI&&SamasaSemanticRelation.PROPER_NAME in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.DA,Svara.A,Vyanjana.TA))}
object VibhasaSyavarokabhyamSutra:ActiveSamasantaSutra(144,"विभाषा श्यावारोकाभ्याम्",true,SamasaType.BAHUVRIHI,40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("श्याव","अरोक")&&c.uttaraPada.upadesha=="दन्त";override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.DA,Svara.A,Vyanjana.TA))}
object AgrantasuddhasubhravrsavarahebhyasCaSutra:ActiveSamasantaSutra(145,"अग्रान्तशुद्धशुभ्रवृषवराहेभ्यश्च",true,SamasaType.BAHUVRIHI,40){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&(c.purvaPada.varnas.takeLast(4)==listOf(Svara.A,Vyanjana.GA,Vyanjana.RA,Svara.A)||c.purvaPada.upadesha in setOf("शुद्ध","शुभ्र","वृष","वराह"))&&c.uttaraPada.upadesha=="दन्त";override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,listOf(Vyanjana.DA,Svara.A,Vyanjana.TA))}
object KakudasyavasthayamLopahSutra:ActiveSamasantaSutra(146,"ककुदस्यावस्थायां लोपः",samasaType=SamasaType.BAHUVRIHI,priority=30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.uttaraPada.upadesha=="ककुद"&&SamasaSemanticRelation.ANIMAL_CONDITION in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1))}
object TrikakutParvateSutra:ActiveSamasantaSutra(147,"त्रिककुत् पर्वते",samasaType=SamasaType.BAHUVRIHI,priority=60){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha=="त्रि"&&c.uttaraPada.upadesha=="ककुद"&&SamasaSemanticRelation.PROPER_NAME in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1))}
object UdvibhyamKakudasyaSutra:ActiveSamasantaSutra(148,"उद्विभ्यां काकुदस्य",samasaType=SamasaType.BAHUVRIHI,priority=50){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("उत्","वि")&&c.uttaraPada.upadesha=="ककुद";override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1))}
object PurnadVibhasaSutra:ActiveSamasantaSutra(149,"पूर्णाद्विभाषा",true,SamasaType.BAHUVRIHI,50){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha=="पूर्ण"&&c.uttaraPada.upadesha=="ककुद";override fun apply(c:SamasaRuleContext)=formedWithFinalMember(c,c.uttaraPada.varnas.dropLast(1))}

object InahStriyamSutra:ActiveSamasantaSutra(152,"इनः स्त्रियाम्",samasaType=SamasaType.BAHUVRIHI,priority=30){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.outputLinga==Linga.STRI&&c.uttaraPada.varnas.takeLast(2)==listOf(Svara.I,Vyanjana.NA);override fun apply(c:SamasaRuleContext)=formedWithAffix(c,SamasantaAffix.KAP)}
object SesadVibhasaCanonicalSutra:ActiveSamasantaSutra(154,"शेषाद्विभाषा",true,SamasaType.BAHUVRIHI,5){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&SamasaSemanticRelation.RESIDUAL_KAP_OPTION in c.semanticRelations;override fun apply(c:SamasaRuleContext)=formedWithAffix(c,SamasantaAffix.KAP)}
object NaSamjnayamSutra:Sutra<SamasaRuleContext,SamasaRuleResult>(number="5.4.155",text="न संज्ञायाम्",hindiExplanation="संज्ञा में कप् का निषेध होता है।",type=SutraType.NISHEDHA,chapter=5,pada=4,optional=false,kramaValue=540155,role=SutraRole.Niyama,action=SutraAction.NISHEDHA,scope=SutraScope.DERIVATION,samasaType=SamasaType.BAHUVRIHI,samasaPriority=80),SamasaSutra{override fun matches(c:SamasaRuleContext)=c.samasaType==SamasaType.BAHUVRIHI&&SamasaSemanticRelation.PROPER_NAME in c.semanticRelations;override fun apply(c:SamasaRuleContext)=SamasaRuleResult.NotApplicable}
object IyasasCaSutra:Sutra<SamasaRuleContext,SamasaRuleResult>(number="5.4.156",text="ईयसश्च",hindiExplanation="ईयस्-अन्त बहुव्रीहि में कप् का निषेध होता है।",type=SutraType.NISHEDHA,chapter=5,pada=4,optional=false,kramaValue=540156,role=SutraRole.Niyama,action=SutraAction.NISHEDHA,scope=SutraScope.DERIVATION,samasaType=SamasaType.BAHUVRIHI,samasaPriority=80),SamasaSutra{override fun matches(c:SamasaRuleContext)=SamasaMorphologicalFeature.IYAS_ENDING in c.uttaraPada.morphologicalFeatures;override fun apply(c:SamasaRuleContext)=SamasaRuleResult.NotApplicable}
object VanditeBhratuhSutra:Sutra<SamasaRuleContext,SamasaRuleResult>(number="5.4.157",text="वन्दिते भ्रातुः",hindiExplanation="वन्दित भ्रातृ-अर्थ में कप् का निषेध होता है।",type=SutraType.NISHEDHA,chapter=5,pada=4,optional=false,kramaValue=540157,role=SutraRole.Niyama,action=SutraAction.NISHEDHA,scope=SutraScope.DERIVATION,samasaType=SamasaType.BAHUVRIHI,samasaPriority=80),SamasaSutra{override fun matches(c:SamasaRuleContext)=c.uttaraPada.upadesha=="भ्रातृ"&&SamasaSemanticRelation.PRAISED_REFERENT in c.semanticRelations;override fun apply(c:SamasaRuleContext)=SamasaRuleResult.NotApplicable}
object RtasChandasiSutra:Sutra<SamasaRuleContext,SamasaRuleResult>(number="5.4.158",text="ऋतश्छन्दसि",hindiExplanation="छन्दस् में ऋकारान्त बहुव्रीहि में कप् का निषेध होता है।",type=SutraType.NISHEDHA,chapter=5,pada=4,optional=false,kramaValue=540158,role=SutraRole.Niyama,action=SutraAction.NISHEDHA,scope=SutraScope.DERIVATION,samasaType=SamasaType.BAHUVRIHI,samasaPriority=80),SamasaSutra{override fun matches(c:SamasaRuleContext)=shortRFinal(c.uttaraPada)&&SamasaSemanticRelation.VEDIC_REGISTER in c.semanticRelations;override fun apply(c:SamasaRuleContext)=SamasaRuleResult.NotApplicable}
object NaditantryohSvangeSutra:Sutra<SamasaRuleContext,SamasaRuleResult>(number="5.4.159",text="नाडीतन्त्र्योः स्वाङ्गे",hindiExplanation="स्वाङ्गवाची नाडी और तन्त्री में कप् का निषेध होता है।",type=SutraType.NISHEDHA,chapter=5,pada=4,optional=false,kramaValue=540159,role=SutraRole.Niyama,action=SutraAction.NISHEDHA,scope=SutraScope.DERIVATION,samasaType=SamasaType.BAHUVRIHI,samasaPriority=80),SamasaSutra{override fun matches(c:SamasaRuleContext)=c.uttaraPada.upadesha in setOf("नाडी","तन्त्री")&&SamasaSemanticRelation.BODY_PART in c.semanticRelations;override fun apply(c:SamasaRuleContext)=SamasaRuleResult.NotApplicable}
object NispravanisCaSutra:ActiveSamasantaSutra(160,"निष्प्रवाणिश्च",samasaType=SamasaType.BAHUVRIHI,priority=90){override fun matches(c:SamasaRuleContext)=c.padas.size>=2&&c.purvaPada.upadesha in setOf("निस्","निष्")&&c.uttaraPada.upadesha=="प्रवाणी";override fun apply(c:SamasaRuleContext)=formedWithMembers(c,mapOf(0 to listOf(Vyanjana.NA,Svara.I,Vyanjana.SSA),c.padas.lastIndex to (c.uttaraPada.varnas.dropLast(1)+Svara.I)))}
