package dev.panini.ashtadhyayi.adhyaya6.pada3

import dev.panini.sutra.Sutra

object Adhyaya6Pada3 {
    val sutras: List<Sutra<*, *>> = listOf(
        AlukUttarapadeSutra,
        PancamyahStokadibhyahSutra,
        ManasahSamjnayamSutra,
        AtmanascaPuraneSutra,
        TatpuruseKrtiBahulamSutra,
        PutreNyatarasyamSutra,
        RtoVidyaYoniSambandhebhyahSutra,
        VibhashaSvasrPatyorSutra,
        AnangRtoDvandveSutra,
        DevataDvandveCaSutra,
        IdAgnehSomavarunayohSutra,
        DivoDyavaSutra,
        DivasChaSutra,
        UsasaUsasahSutra,
        MatariPitariChaSutra,
        PitramataSutra,
        StriyahPumvadBhasitapumskatSutra,
        PumvatKarmadharayaJatiyaDesiyesuSutra,
        GharupaKalpaCeladBruvaSutra,
        NadyahSesasyanyatarasyamSutra,
        UgitashCaSutra,
        MahatahSamanadhikaranaSutra,
        HrdayasyaHrllekhayadanalasesuSutra,
        VaSokasyanRogesuSutra,
        PadasyaPadajyatigopahatesuSutra,
        HimakasihatisuCaSutra,
        VaGhosamisrasabdesuSutra,
        UdakasyodahSamjnayamSutra,
        PesamVasaVahanaDhisuCaSutra,
        EkahaladauPurayitavyeAnyatarasyamSutra,
        ManthaudanaSaktuBinduVajraSutra,
        DvyashtanahSankhyayamSutra,
        TreStrayahSutra,
        VibhashaChatvarimshatPrabhritauSarveshamSutra,
        NalopoNanjahSutra,
        TasmanNudAciSutra,
        NabhraanNapaanNavedaSutra,
        SahasyaSahSamjnayamSutra,
        GranthantadhikeCaSutra,
        DvitiyeCanupakhyeSutra,
        AvyayibhaveCakaleSutra,
        EkadishCaikasyaCadukSutra,
        VopasarjanasyaSutra,
        DhralopePurvasyaDirghonahSutra,
    )
}
